### ISSUE TITLE
Problem creating a Transaction

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore#1024]
```
var b = require('bitcore');
var inputs = [ { txid: '008cb24ad6c8d81d95a0342d0a05170442aa3a385887bf2ef757a22312055dc2',
       vout: 1,
       amount: 100,
       scriptPubKey: 'OP_2 33 0x0319008ffe1b3e208f5ebed8f46495c056763f87b07930a7027a92ee477fb0cb0f 33 0x03b5f035af8be40d0db5abb306b7754949ab39032cf99ad177691753b37d101301 OP_2 OP_CHECKMULTISIG' } ];

var t = new b.Transaction();
t.from(inputs);
```

output:
```
buffer.js:348
      ret = this.parent.hexWrite(string, this.offset + offset, length);
                        ^
TypeError: Invalid hex string
    at Buffer.write (buffer.js:348:25)
    at new Buffer (buffer.js:215:28)
    at PublicKeyHashInput.Input._fromObject
```

with:
```
var b = require('bitcore');

var inputs = [ { txid: '008cb24ad6c8d81d95a0342d0a05170442aa3a385887bf2ef757a22312055dc2',
       vout: 1,
       amount: 100,

       scriptPubKey: '52210319008ffe1b3e208f5ebed8f46495c056763f87b07930a7027a92ee477fb0cb0f2103b5f035af8be40d0db5abb306b7754949ab39032cf99ad177691753b37d10130152ae',

} ];

var t = new b.Transaction();
t.from(inputs);
```
I get:
```

buffer.js:348
      ret = this.parent.hexWrite(string, this.offset + offset, length);
                        ^
TypeError: Invalid hex string
    at Buffer.write (buffer.js:348:25)
    at new Buffer (buffer.js:215:28)
    at PublicKeyHashInput.Input._fromObject
```

**Comment by eordano** [comment]
The issue is because of an invalid usage of `from`.

We should have a more descriptive error message for this, as it's an unsupported kind of output

**Comment by matiu** [comment]
Please also look this case:
```
var b = require('bitcore');

var inputs = [ { txid: '55563942753389284bd933f64be51b87ef374941802ca71a91a95e63fbfb4ce',
       vout: 1,
       amount: 100,
       scriptPubKey: 'OP_HASH160 20 0xa8a9648754fbda1b6c208ac9d4e252075447f368 OP_EQUAL',
} ];

var t = new b.Transaction();

t.from(inputs);
```

it is a p2sh scriptPubKey. From here:
http://bitcore.io/api/transaction/transaction.html
It seems that "OP_HASH160 20 0xa8a9648754fbda1b6c208ac9d4e252075447f368 OP_EQUAL" should be accepted. Changing the scriptPubKey to:
"a914a8a9648754fbda1b6c208ac9d4e252075447f36887"  works as expected.

**Comment by braydonf** [comment]
Because of the multiple utxos?

**Comment by eordano** [comment]
Because the output that was trying to be spent was a multisig normal output (no P2SH). I think this was improved here (no more cryptic error): https://github.com/bitpay/bitcore/commit/bd97f20f1c851f9eabf7f042e6b735b659600703 but it won't fail early. I'll add a better check.

**Comment by eordano** [comment]
This doesn't fail any more and will have a better error message here: https://github.com/bitpay/bitcore/pull/1046
