### ISSUE TITLE
compatibility with sandboxed-module

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1153]
```javascript
var sandboxed = require('sandboxed-module');
var bitcore = sandboxed.require('bitcore');
```

Results in an error:

```
TypeError: Cannot read property 'prototype' of undefined
    at runInContext (bitcore-sandboxed/node_modules/bitcore/node_modules/lodash/dist/lodash.js:460:29)
    at Object.<anonymous> (bitcore-sandboxed/node_modules/bitcore/node_modules/lodash/dist/lodash.js:6755:11)
    at Object.<anonymous> (bitcore-sandboxed/node_modules/bitcore/node_modules/lodash/dist/lodash.js:6785:3)
    at SandboxedModule._compile (bitcore-sandboxed/node_modules/sandboxed-module/lib/sandboxed_module.js:251:19)
    at createInnerSandboxedModule (bitcore-sandboxed/node_modules/sandboxed-module/lib/sandboxed_module.js:183:23)
    at SandboxedModule.RecursiveRequireProxy (bitcore-sandboxed/node_modules/sandboxed-module/lib/sandboxed_module.js:214:27)
    at Object.<anonymous> (bitcore-sandboxed/node_modules/bitcore/lib/errors/index.js:3:9)
    at SandboxedModule._compile (bitcore-sandboxed/node_modules/sandboxed-module/lib/sandboxed_module.js:251:19)
    at createInnerSandboxedModule (bitcore-sandboxed/node_modules/sandboxed-module/lib/sandboxed_module.js:183:23)
    at SandboxedModule.RecursiveRequireProxy (bitcore-sandboxed/node_modules/sandboxed-module/lib/sandboxed_module.js:214:27)
```

**Comment by eordano** [comment]
Are we sure we want to use this?

```This module is intended to ease dependency injection for unit testing. However, feel free to use it for whatever crimes you can think of.```

**Comment by braydonf** [comment]
This came up because of testing, and being able to reset Networks, but has since been resolved with https://github.com/bitpay/bitcore/commit/4390b08b484137c9e9c389078ccadcc2f1a592a0
