### ISSUE TITLE
Version checking not working?

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore#1170]
```
/Users/ematiu/devel/bwc/node_modules/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore/index.js:17
  throw new Error(message);
        ^
Error: More than one instance of bitcore found with different versions: v0.11.6 and v0.11.6. Make sure there are no version conflicts between package.json files of your dependencies. This could also happen when a package depends on a git repository.
    at Object.<anonymous> (/Users/ematiu/devel/bwc/node_modules/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore/index.js:17:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
   
[...]
```

```
find . -name bitcore -type d
./node_modules/bitcore-payment-protocol/node_modules/bitcore
./node_modules/bitcore-wallet-service/node_modules/bitcore-explorers/node_modules/bitcore
./node_modules/bitcore-wallet-utils/node_modules/bitcore
```

cat of the related package.json files returns:
  "version": "0.11.6",
on the 3 files.

From:
https://github.com/matiu/bitcore-wallet-client/commit/088012a21f8e723ede7a43eb42bdaa58ee8a6d11

**Comment by maraoz** [comment]
This was fixed by including `bitcore` as a dependency for the root project. @matiu if you need further help  reopen the issue
