### ISSUE TITLE
Script.fromBufferReader and script.toBufferWriter not implemented.

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore#1176]
Refactoring to use Script.fromBufferReader and script.toBufferWriter may simplify serialization, so that https://github.com/bitpay/bitcore/blob/master/lib/transaction/output.js#L105 could be written as:
```javascript
Output.fromBufferReader = function(br) {
  var obj = {};
  obj.satoshis = br.readUInt64LEBN();
  obj.script = Script.fromBufferReader(br);
  var output = new Output(obj);
  return output;
};
```

**Comment by fanatid** [comment]
In this case Script may throw Error and you don't get parsed block or transaction... ( #1195 )

**Comment by fanatid** [comment]
btw, you can see this problem in `bitcoinjs-lib@1.4.3`

```js
> require('bitcoinjs-lib').Transaction.fromHex('0100000001cbf75e37f8f57f338dd435d564c7302a02d9c6d03e26c8f0f24fa46052c0c0d1010000008b48304502210095cf913f96c52242b3a88dc59a9aed2a568dc80446541348c89c5430727d548402206adbe00b00db7d71458b990ab69090a038244a6b94faca98652656fd0b9be4e4014104dac5c4da1fd483b8655ab6a5d8e5dd2226ef20d1023d7ff38df29bfa8fcfdf73fb99a07efa0c66112c1fa438a8ed8571364bc04f21eaadf54c4918d43aba8ed3ffffffff02804f1200000000001976a914d40f073684cfac11be0366dc6a56a8d3cc87ece488ac1027000000000000044e6f6e6500000000')
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt32LE (buffer.js:609:5)
...
```

**Comment by braydonf** [comment]
Yep, scripts can not always be instantiated, and these methods are not needed.
