### ISSUE TITLE
gulp browser fails

### ISSUE THREAD

**Issue by JustinDrake** [bitpay/bitcore#1211]
```
$ gulp browser

Error: Cannot find module 'bitcore-build'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/justin/bitcore/gulpfile.js:3:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by maraoz** [comment]
did you run `npm install` first?

**Comment by braydonf** [comment]
Testing a fresh install and `gulp browser` works correctly after running `npm install` please reopen if there is still an issue, or open a topic on https://labs.bitpay.com/c/bitcore

**Comment by snakecharmer1024** [comment]
This needs to be put in the readme. I looked around for quite a while before I found this. 

npm install bitcore != npm install

**Comment by braydonf** [comment]
Included in: https://github.com/bitpay/bitcore/pull/1273
