### ISSUE TITLE
sudo cnpm install -g bitcore install failed: Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by gclsoft** [bitpay/bitcore#1372]
`sudo cnpm install -g bitcore ` install failed

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libbitcoind.a(libbitcoind_la-strnlen.o) has no symbols
libtool: link: ( cd ".libs" && rm -f "libbitcoind.la" && ln -s "../libbitcoind.la" "libbitcoind.la" )
make[1]: Nothing to be done for `all-am'.
Creating the sha marker for the patching in libbitcoind...
Writing patch sha file to: "/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/bin/../cache/patch_sha.txt"
/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/libbitcoind /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/libbitcoind
/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/libbitcoind
Build finished successfully.
make: *** No rule to make target `Release/obj.target/libbitcoind/src/libbitcoind.o', needed by `Release/bitcoind.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! bitcore-node@1.0.0 install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0 install script.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/apple/.cnpmrc" "--disturl=https://npm.taobao.org/dist" "--cache=/Users/apple/.npm/.cache_cnpm" "--registry=https://registry.npm.taobao.org" "install" "-g" "bitcore"
npm ERR! cwd /Users/apple/node/undo4096/tool/videoPei
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.20
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/apple/node/undo4096/tool/videoPei/npm-debug.log
npm ERR! not ok code 0
```

**Comment by braydonf** [comment]
Node.js version v0.10.28 isn't supported, try using 0.12.7 or 4.2.2

**Comment by braydonf** [comment]
Also see: https://github.com/bitpay/bitcore-node/issues/350

**Comment by gclsoft** [comment]
still error node -v
v4.2.2:
```
Build finished successfully.
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   '--debug=false',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.0.3
gyp info using node@4.2.2 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.2.2
gyp verb command install [ '4.2.2' ]
gyp verb install input version string "4.2.2"
gyp verb install installing version: 4.2.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 4.2.2
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/build
gyp verb build dir "build" dir needed to be created? /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/config.gypi
gyp verb common.gypi checking for gypi file: /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/apple/.node-gyp/4.2.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/apple/.node-gyp/4.2.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/apple/.node-gyp/4.2.2
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/libbitcoind/src/libbitcoind.o', needed by `Release/bitcoind.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm verb unsafe-perm in lifecycle true
npm info bitcore-node@1.0.0 Failed to exec install script
npm verb unlock done using /Users/apple/.cnpm/_locks/bitcore-node-c86ad0be8a9579e9.lock for /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
npm verb about to build /usr/local/lib/node_modules/bitcore
npm verb unlock done using /Users/apple/.cnpm/_locks/bitcore-29fe77c260096d1a.lock for /usr/local/lib/node_modules/bitcore
npm verb stack Error: bitcore-node@1.0.0 install: `./bin/install`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid bitcore-node@1.0.0
npm verb cwd /Users/apple
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/apple/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/apple/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "--unsafe-perm" "--verbose" "-g" "bitcore"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.0 install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0 install script './bin/install'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild lib/node_modules/bitcore/node_modules/bitcore-node
npm info preuninstall bitcore-node@1.0.0
npm info uninstall bitcore-node@1.0.0
npm verb unbuild rmStuff bitcore-node@1.0.0 from /usr/local/lib/node_modules
npm verb unbuild rmStuff in /usr/local/lib/node_modules/bitcore/node_modules
npm verb gentlyRm vacuuming from /usr/local/lib/node_modules/bitcore/node_modules/.bin/bitcore-node up to /usr/local
npm info postuninstall bitcore-node@1.0.0
npm verb gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
npm verb unbuild lib/node_modules/bitcore
npm info preuninstall bitcore@2.0.0
npm info uninstall bitcore@2.0.0
npm verb unbuild rmStuff bitcore@2.0.0 from /usr/local/lib/node_modules
npm verb gentlyRm vacuuming from /usr/local/bin/bitcore up to /usr/local
npm verb gentlyRm vacuuming from /usr/local/bin/bitcored up to /usr/local
npm info postuninstall bitcore@2.0.0
npm verb gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/bitcore

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log
bogon:~ apple$ node -v
v4.2.2
bogon:~ apple$ npm -v
2.14.7
```

**Comment by gclsoft** [comment]
```
Build finished successfully.
make: *** No rule to make target `Release/obj.target/libbitcoind/src/libbitcoind.o', needed by `Release/bitcoind.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/apple/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/apple/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "-g" "bitcore"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.0 install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0 install script './bin/install'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log
bogon:~ apple$ 
```
Tried again and failed.

**Comment by braydonf** [comment]
Looks like there is an error earlier in the install as `libbitcoind.o` isn't found. However there shouldn't need to be a build. Are you trying to build from source? If so, please take a look at: https://bitcore.io/api/build

**Comment by braydonf** [comment]
Also since you've previously tried to install with Node.js v0.10, make sure to do a fresh install.

**Comment by gclsoft** [comment]
Thanks @braydonf , but still build source error:
```
~/Downloads/bitcore-master/node_modules/bitcore-node/libbitcoind
./autogen.sh
aclocal: error: aclocal: file '/usr/local/share/aclocal/ksba.m4' does not exist
autoreconf: aclocal failed with exit status: 1
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.0 install: `./bin/install`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0 install script './bin/install'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Downloads/bitcore-master/npm-debug.log
```

**Comment by braydonf** [comment]
When running `npm install` in a git clone of `bitcore`, you should see something such as:
```
Downloading binary: https://bitcore-node.s3.amazonaws.com/libbitcoind-1.0.0-node46-darwin-x64.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5854k  100 5854k    0     0  2645k      0  0:00:02  0:00:02 --:--:-- 2645k
Unpacking binary distribution
x build/Release/bitcoind.node
x build/Release/bitcoind.node.sig
bitcore-node@1.0.0 node_modules/bitcore-node
```

**Comment by gclsoft** [comment]
@braydonf Yes, I am trying that way, but failed again:
```
Build finished successfully.
2015-11-18 01:17:29.701 xcodebuild[54030:118411] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
make: *** No rule to make target `Release/obj.target/libbitcoind/src/libbitcoind.o', needed by `Release/bitcoind.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/apple/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/apple/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "i" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.0 install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0 install script './bin/install'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Downloads/bitcore-master/npm-debug.log
```

**Comment by braydonf** [comment]
Which file does it try to download before it starts to build?

**Comment by gclsoft** [comment]
Many files, at last 5 files need to download every time I tried to install.
Like this: Downloading binary: https://bitcore-node.s3.amazonaws.com/libbitcoind-1.0.0-dev-node46-darwin-x64.tgz

```
2015-11-18 02:13:04.222 xcodebuild[98081:188738] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
make: *** No rule to make target `Release/obj.target/libbitcoind/src/libbitcoind.o', needed by `Release/bitcoind.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bitcore-node
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/apple/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/apple/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.0-dev install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0-dev install script './bin/install'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Downloads/bitcore-node/npm-debug.log
```

**Comment by braydonf** [comment]
Okay, so it looks like you are on a development version (and not a released version) for bitcore-node, and hence why it's trying to build.

**Comment by gclsoft** [comment]
Thanks solved by download v2.0 brach

**Comment by gclsoft** [comment]
@braydonf On mac it is ok now, but on centos 6, it still failed:
I've install both from https://github.com/bitpay/bitcore v2.0 and https://github.com/bitpay/bitcore-node v2.0, both install ok but run error:
```
[root@li704-245 bitcore-node-0.2.0]# npm start

> bitcore-node@0.2.0 start /root/work/bitcore-node-0.2.0
> node bin/start.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/work/bitcore-node-0.2.0/lib/node.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by braydonf** [comment]
Spawned an issue regarding centos: https://github.com/bitpay/bitcore-node/issues/361 as from what I know, there hasn't been testing or documentation here yet.
