### ISSUE TITLE
'bitcore call getAddressSummary' fails

### ISSUE THREAD

**Issue by demonhjack** [bitpay/bitcore#1391]
bitcore call getAddressSummary [address] fails with this log:
[2016-03-01T18:12:01.844Z] error: uncaught exception: [TypeError: undefined is not a function]
[2016-03-01T18:12:01.846Z] error: TypeError: undefined is not a function
    at /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/address/index.js:1362:5
    at /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by braydonf** [comment]
Please see:
- https://github.com/bitpay/bitcore-node/issues/432
- https://github.com/bitpay/bitcore-node/pull/440
