### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by Bitcoinsis** [bitpay/bitcore#1398]
I am installing bitcore on fresh ubuntu 14.04 server but i am having this error can you please guide me how to resolve

```
npm install -g bitcore
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/leveldown#bitpay-1.4.4 resetting remote /root/.npm/_git-remotes/git-github-com-bitpay-leveldown-git-3f2e80dc because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/socket.io#bitpay-1.3.7 resetting remote /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-git-2b6acbb0 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/socket.io-client#bitpay-1.3.7 resetting remote /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-client-git-01902db7 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bitpay/socket.io-client.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-client-git-01902db7: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bitpay/socket.io-client.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-client-git-01902db7: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bitpay/leveldown.git /root/.npm/_git-remotes/git-github-com-bitpay-leveldown-git-3f2e80dc: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bitpay/leveldown.git /root/.npm/_git-remotes/git-github-com-bitpay-leveldown-git-3f2e80dc: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bitpay/socket.io.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-git-2b6acbb0: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bitpay/socket.io.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-git-2b6acbb0: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/socket.io-client#bitpay-1.3.7 resetting remote /root/.npm/_git-remotes/https-github-com-bitpay-socket-io-client-git-cfb3a211 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/leveldown#bitpay-1.4.4 resetting remote /root/.npm/_git-remotes/https-github-com-bitpay-leveldown-git-c8dff8ba because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/socket.io#bitpay-1.3.7 resetting remote /root/.npm/_git-remotes/https-github-com-bitpay-socket-io-git-fa2db72a because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/bitpay/socket.io-client.git /root/.npm/_git-remotes/https-github-com-bitpay-socket-io-client-git-cfb3a211: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/bitpay/socket.io-client.git /root/.npm/_git-remotes/https-github-com-bitpay-socket-io-client-git-cfb3a211: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/bitpay/leveldown.git /root/.npm/_git-remotes/https-github-com-bitpay-leveldown-git-c8dff8ba: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/bitpay/leveldown.git /root/.npm/_git-remotes/https-github-com-bitpay-leveldown-git-c8dff8ba: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/bitpay/socket.io.git /root/.npm/_git-remotes/https-github-com-bitpay-socket-io-git-fa2db72a: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/bitpay/socket.io.git /root/.npm/_git-remotes/https-github-com-bitpay-socket-io-git-fa2db72a: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/socket.io-client#bitpay-1.3.7 resetting remote /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-client-git-72a8c7a0 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/socket.io#bitpay-1.3.7 resetting remote /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-git-0cdc480d because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /root/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  bitpay/leveldown#bitpay-1.4.4 resetting remote /root/.npm/_git-remotes/git-github-com-bitpay-leveldown-git-01a43d3a because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/socket.io-client.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-client-git-72a8c7a0: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/socket.io-client.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-client-git-72a8c7a0: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/socket.io.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-git-0cdc480d: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/socket.io.git /root/.npm/_git-remotes/git-github-com-bitpay-socket-io-git-0cdc480d: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/leveldown.git /root/.npm/_git-remotes/git-github-com-bitpay-leveldown-git-01a43d3a: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:bitpay/leveldown.git /root/.npm/_git-remotes/git-github-com-bitpay-leveldown-git-01a43d3a: undefined
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/root/.nvm/versions/node/v4.4.3/bin/node" "/root/.nvm/versions/node/v4.4.3/bin/npm" "install" "-g" "bitcore"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by dabura667** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm...

I'm not too good at English, but I'd guess that you need to install git.

Just an idea.

**Comment by braydonf** [comment]
> Note: Do not run this command with sudo or with root privileges as this will lead to permission issues.
https://bitcore.io/guides/full-node
