### ISSUE TITLE
Error: EACCES: permission denied, scandir '/home'

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore#1407]
Dear Sirs,
I need to install bitcore on Linux server with straight security requirements.
I have not read/write permissions of /home directory
I installed bitcore in my home directory locally using 
`npm install bitcore`
But now when I try to create node with 
`bitcore create mynode --testnet`
I get following error:

```
/home/develop/bitcore/node_modules/glob/sync.js:321
        throw er
        ^

Error: EACCES: permission denied, scandir '/home'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at GlobSync._readdir (/home/develop/bitcore/node_modules/glob/sync.js:275:41)
    at GlobSync._processReaddir (/home/develop/bitcore/node_modules/glob/sync.js:135:22)
    at GlobSync._process (/home/develop/bitcore/node_modules/glob/sync.js:130:10)
    at new GlobSync (/home/develop/bitcore/node_modules/glob/sync.js:46:10)
    at Function.globSync [as sync] (/home/develop/bitcore/node_modules/glob/sync.js:24:10)
    at /home/develop/bitcore/node_modules/findup-sync/lib/findup-sync.js:31:19
    at Array.map (native)
    at module.exports (/home/develop/bitcore/node_modules/findup-sync/lib/findup-sync.js:30:22)

```

How can I prevent scandir /home say change it to ~/ ?

Thanks in advance,
Igor

**Comment by braydonf** [comment]
What's your current working directory?

**Comment by igorvlassov** [comment]
My home directory is /home/develop
I installled bitcore into ~/bitcore
So I have ~/bitcore/node_modules
And I trying to create testnode in ~/bitcore
with command
` ~/bitcore/node_modules/.bin/bitcore create testnode --testnet`

**Comment by braydonf** [comment]
And this doesn't output `/home` ?
```
echo $PWD
```

**Comment by DanielRHayes** [comment]
closing stale issue

**Comment by PrakashLakhara** [comment]
Why you closed it?
