### ISSUE TITLE
Unable to install bitcore 4.1 on win10 x64

### ISSUE THREAD

**Issue by manuel-di-iorio** [bitpay/bitcore#1422]
Trying to install the latest version of bitcore on win10 (with visual studio 14 and python 2.7 installed)

`> npm i -S bitcore@latest --force`

```
npm WARN using --force I sure hope you know what you are doing.

> bitcore-node@3.1.2 preinstall D:\folder\node_modules\bitcore\node_modules\bitcore-node
> ./scripts/download

"." non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.

> zmq@2.15.3 install D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq
> node-gyp rebuild

\
D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
  binding.cc
..\binding.cc(673): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(674): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(675): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(676): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(677): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(678): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(679): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(680): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(681): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\Paym
eabit\pb-be-prod\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(682): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(696): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(697): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(698): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(699): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(700): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(701): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(702): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(703): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(704): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(705): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(1140): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(1285): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
..\binding.cc(1286): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
d:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\node_modules\nan\nan_new.h(208)
: warning C4244: 'argument': conversion from 'int64_t' to 'double', possible loss of data [D:\folder\node
_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
  ..\binding.cc(624): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number
  ,T>(A0)' being compiled
          with
          [
              T=int64_t,
              A0=int64_t
          ]
  ..\binding.cc(678): note: see reference to function template instantiation 'v8::Local<v8::Value> zmq::Socket::GetSock
  Opt<int64_t>(int)' being compiled
d:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\node_modules\nan\nan_new.h(208)
: warning C4244: 'argument': conversion from 'uint64_t' to 'double', possible loss of data [D:\folder\nod
e_modules\bitcore\node_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
  ..\binding.cc(624): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number
  ,T>(A0)' being compiled
          with
          [
              T=uint64_t,
              A0=uint64_t
          ]
  ..\binding.cc(680): note: see reference to function template instantiation 'v8::Local<v8::Value> zmq::Socket::GetSock
  Opt<uint64_t>(int)' being compiled
  win_delay_load_hook.c
C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error
C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [D:\folder\node_modules\bitcore\node
_modules\bitcore-node\node_modules\zmq\build\zmq.vcxproj]
  D:\Apps\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Manuel\\AppData\\Roaming\\nvm\\v4.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\zmq
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok

> bufferutil@1.2.1 install D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\bufferutil
> node-gyp rebuild


D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
  bufferutil.cc
  win_delay_load_hook.c
C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error
C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [D:\folder\node_modules\bitcore\node
_modules\bitcore-node\node_modules\bufferutil\build\bufferutil.vcxproj]
  D:\Apps\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Manuel\\AppData\\Roaming\\nvm\\v4.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\bufferutil
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok

> utf-8-validate@1.2.1 install D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\utf-8-validate
> node-gyp rebuild


D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
  validation.cc
  win_delay_load_hook.c
C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error
C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [D:\folder\node_modules\bitcore\node
_modules\bitcore-node\node_modules\utf-8-validate\build\validation.vcxproj]
  D:\Apps\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Manuel\\AppData\\Roaming\\nvm\\v4.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\folder\node_modules\bitcore\node_modules\bitcore-node\node_modules\utf-8-validate
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "bitcore@latest" "--force"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! path D:\folder\node_modules\bitcore\node_modules\bitcore-node\bin\bitcoind
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\folder\node_modules\bitcore\node_modules\bitcore-node\bin\bitcoind'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\folder\npm-debug.log

D:\folder>nodemon -q
Error: Cannot find module 'bitcore'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\folder\server\config\config.coffee:3:11)
  at Object.<anonymous> (D:\folder\server\config\config.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.loadFile (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (D:\folder\server\server.coffee:7:10)
  at Object.<anonymous> (D:\folder\server\server.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (C:\Users\Manuel\AppData\Roaming\nvm\v4.4.0\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

Any ideas? :\

**Comment by braydonf** [comment]
Windows is not supported yet, see https://github.com/bitpay/bitcore-node/issues/271
