### ISSUE TITLE
Enabling bitcore-wallet-service with upstart

### ISSUE THREAD

**Issue by shoaibmerchant** [bitpay/bitcore#1429]
I am trying to setup a bitcore full node and set it up as a service using the upstart conf. I have setup by adding bitcore user and the config is in `~/.bitcore`. All additional services like insight-ui insight-api and web work fine but if I add `bitcore-wallet-service` then I need to execute `bitcored` from the node's directory to make it work else it gives an error given below.

```js
Error: Cannot find module 'bitcore-wallet-service/package.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadModule (/usr/lib/node_modules/bitcore/node_modules/bitcore-node/lib/scaffold/start.js:143:26)
    at Function.setupServices (/usr/lib/node_modules/bitcore/node_modules/bitcore-node/lib/scaffold/start.js:181:7)
    at start (/usr/lib/node_modules/bitcore/node_modules/bitcore-node/lib/scaffold/start.js:85:31)
    at Object.main [as daemon] (/usr/lib/node_modules/bitcore/node_modules/bitcore-node/lib/cli/daemon.js:34:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/bitcore/node_modules/bitcore-node/lib/cli/bitcored.js:32:16)
    at Liftoff.<anonymous> (/usr/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/liftoff/index.js:202:12)
```

Steps to reproduce:
1. Setup a bitcore full node with config in home directory
2. Add bitcore-wallet-service
3. Run `bitcored` from node's directory it works
4. Run `bitcored` from any other directory and it **fails**.

Note: I have setup Setup upstart config using `https://github.com/bitpay/bitcore/blob/master/scripts/debian/bitcore.conf` the tutorial on https://bitcore.io/guides/upstart-daemon is outdated.

**Comment by dabura667** [comment]
Between restart and script add a line that says

chdir /abs/path/to/your/directory

This will set the working directory for your upstart script.

Most likely there was a require that was using relative importing somewhere.

**Comment by shoaibmerchant** [comment]
Alright thanks, sorry I didn't see this earlier. I will try this out and get back.
