### ISSUE TITLE
 RangeError: Index out of range

### ISSUE THREAD

**Issue by diadal** [bitpay/bitcore#1433]
Urgent help on below issue

error: uncaught exception: RangeError: Index out of range
    at checkOffset (buffer.js:816:11)
    at Buffer.readUInt32LE (buffer.js:878:5)
    at BufferReader.readUInt32LE (/Users/administrator/.bitco/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
    at Transaction.fromBufferReader (/Users/administrator/.bitco/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
    at Transaction.fromBuffer (/Users/administrator/.bitco/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at InsightAPI.transactionEventHandler (/Users/administrator/.bitco/node_modules/insight-api/lib/index.js:267:30)
    at emitOne (events.js:96:13)
    at Bitcoin.emit (events.js:188:7)
    at Bitcoin._zmqTransactionHandler (/Users/administrator/.bitco/node_modules/bitcore-node/lib/services/bitcoind.js:639:10)
    at .<anonymous> (/Users/administrator/.bitco/node_modules/bitcore-node/lib/services/bitcoind.js:713:12)
[2016-11-27T06:54:27.598Z] error: RangeError: Index out of range
    at checkOffset (buffer.js:816:11)
    at Buffer.readUInt32LE (buffer.js:878:5)
    at BufferReader.readUInt32LE (/Users/administrator/.bitco/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
    at Transaction.fromBufferReader (/Users/administrator/.bitco/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
    at Transaction.fromBuffer (/Users/administrator/.bitco/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at InsightAPI.transactionEventHandler (/Users/administrator/.bitco/node_modules/insight-api/lib/index.js:267:30)
    at emitOne (events.js:96:13)
    at Bitcoin.emit (events.js:188:7)
    at Bitcoin._zmqTransactionHandler (/Users/administrator/.bitco/node_modules/bitcore-node/lib/services/bitcoind.js:639:10)
    at .<anonymous> (/Users/administrator/.bitco/node_modules/bitcore-node/lib/services/bitcoind.js:713:12)
[2016-11-27T06:54:27.598Z] info: Beginning shutdown
[2016-11-27T06:54:27.598Z] info: Stopping insight-ui
[2016-11-27T06:54:27.598Z] info: Stopping insight-api
[2016-11-27T06:54:27.598Z] info: Stopping web
[2016-11-27T06:54:27.599Z] info: Stopping bitcoind
[2016-11-27T06:54:38.905Z] error: uncaught exception: RangeError: Index out of range
    at checkOffset (buffer.js:816:11)

**Comment by saroar** [comment]
lol dead group no help same problem here
