### ISSUE TITLE
Bitcore is crashing after "Activating best chain"

### ISSUE THREAD

**Issue by nyanloutre** [bitpay/bitcore#1434]
Since I restarted my bitcore node I can't start it up. This is what I get : 

# Bitcore log
```
[2016-12-08T15:05:18.583Z] info: Using config: /mynode/bitcore-node.json
[2016-12-08T15:05:18.585Z] info: Using network: livenet
[2016-12-08T15:05:18.586Z] info: Starting bitcoind
[2016-12-08T15:05:18.589Z] info: Using bitcoin config file: /mynode/data/bitcoin.conf
[2016-12-08T15:05:18.593Z] info: Starting bitcoin process
[2016-12-08T15:05:23.631Z] warn: Loading block index...
[2016-12-08T15:05:28.640Z] warn: Verifying blocks...
[2016-12-08T15:05:33.646Z] warn: Verifying blocks...
[2016-12-08T15:05:38.653Z] warn: Verifying blocks...
[2016-12-08T15:05:43.661Z] warn: Verifying blocks...
[2016-12-08T15:05:48.663Z] warn: Verifying blocks...
[2016-12-08T15:05:53.669Z] warn: Verifying blocks...
[2016-12-08T15:05:58.673Z] warn: Verifying blocks...
[2016-12-08T15:06:03.680Z] warn: Verifying blocks...
[2016-12-08T15:06:08.686Z] warn: Verifying blocks...
[2016-12-08T15:06:13.691Z] warn: Verifying blocks...
[2016-12-08T15:06:18.698Z] warn: Verifying blocks...
[2016-12-08T15:06:23.702Z] warn: Verifying blocks...
[2016-12-08T15:06:28.705Z] warn: Verifying blocks...
[2016-12-08T15:06:33.711Z] warn: Activating best chain...
[2016-12-08T15:06:38.714Z] warn: Activating best chain...
[2016-12-08T15:06:43.718Z] warn: Activating best chain...
[2016-12-08T15:06:48.725Z] warn: Activating best chain...
[2016-12-08T15:06:53.732Z] warn: Activating best chain...
[2016-12-08T15:06:58.736Z] warn: Activating best chain...
[2016-12-08T15:07:03.739Z] warn: Activating best chain...
[2016-12-08T15:07:08.747Z] warn: Activating best chain...
[2016-12-08T15:07:13.754Z] warn: Activating best chain...
[2016-12-08T15:07:18.761Z] warn: Activating best chain...
[2016-12-08T15:07:23.767Z] warn: Activating best chain...
[2016-12-08T15:07:28.774Z] warn: Activating best chain...
[2016-12-08T15:07:33.781Z] warn: Activating best chain...
[2016-12-08T15:07:38.788Z] warn: Activating best chain...
[2016-12-08T15:07:43.795Z] warn: Activating best chain...
[2016-12-08T15:07:48.802Z] warn: Activating best chain...
[2016-12-08T15:07:53.810Z] warn: Activating best chain...
[2016-12-08T15:07:58.816Z] warn: Activating best chain...
[2016-12-08T15:08:03.823Z] warn: Activating best chain...
[2016-12-08T15:08:08.830Z] warn: Activating best chain...
[2016-12-08T15:08:13.835Z] warn: Activating best chain...
[2016-12-08T15:08:18.843Z] warn: Activating best chain...
[2016-12-08T15:08:23.847Z] warn: Activating best chain...
[2016-12-08T15:08:28.853Z] warn: Activating best chain...
[2016-12-08T15:08:33.860Z] warn: Activating best chain...
[2016-12-08T15:08:38.867Z] warn: Activating best chain...
[2016-12-08T15:08:43.874Z] warn: Activating best chain...
[2016-12-08T15:08:48.883Z] warn: Activating best chain...
[2016-12-08T15:08:53.888Z] warn: Activating best chain...
[2016-12-08T15:08:58.894Z] warn: Activating best chain...
[2016-12-08T15:09:03.901Z] warn: Activating best chain...
[2016-12-08T15:09:08.908Z] warn: Activating best chain...
[2016-12-08T15:09:13.911Z] warn: Activating best chain...
[2016-12-08T15:09:18.959Z] warn: Activating best chain...
[2016-12-08T15:09:23.964Z] warn: Activating best chain...
[2016-12-08T15:09:28.967Z] warn: Activating best chain...
[2016-12-08T15:09:33.975Z] warn: Activating best chain...
[2016-12-08T15:09:38.982Z] warn: Activating best chain...
[2016-12-08T15:09:43.986Z] warn: Activating best chain...
[2016-12-08T15:09:48.991Z] warn: Activating best chain...
[2016-12-08T15:09:53.998Z] warn: Activating best chain...
[2016-12-08T15:09:59.002Z] warn: Activating best chain...
[2016-12-08T15:10:04.009Z] warn: Activating best chain...
[2016-12-08T15:10:09.015Z] warn: Activating best chain...
[2016-12-08T15:10:14.020Z] warn: Activating best chain...
[2016-12-08T15:10:14.022Z] error: Failed to start services
[2016-12-08T15:10:14.023Z] error: RPCError: Activating best chain...
    at Bitcoin._wrapRPCError (/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:449:13)
    at /mynode/node_modules/bitcore-node/lib/services/bitcoind.js:779:28
    at IncomingMessage.<anonymous> (/mynode/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:107:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
[2016-12-08T15:10:14.023Z] info: Beginning shutdown
[2016-12-08T15:10:14.024Z] info: Stopping insight-ui (not started)
[2016-12-08T15:10:14.025Z] info: Stopping bitcore-wallet-service (not started)
[2016-12-08T15:10:14.025Z] info: Stopping insight-api (not started)
[2016-12-08T15:10:14.025Z] info: Stopping web (not started)
[2016-12-08T15:10:14.025Z] info: Stopping bitcoind
[2016-12-08T15:10:26.912Z] error: Failed to stop services: Error: bitcoind spawned process exited with status code: 1
```

# debug.log
```
2016-12-08 15:05:18 Bitcoin version v0.12.1-bitcore-4 (2016-09-20 10:16:42 -0400)
2016-12-08 15:05:18 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2016-12-08 15:05:18 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2016-12-08 15:05:18 Default data directory /root/.bitcoin
2016-12-08 15:05:18 Using data directory /mynode/data
2016-12-08 15:05:18 Using config file /mynode/data/bitcoin.conf
2016-12-08 15:05:18 Using at most 125 connections (1048576 file descriptors available)
2016-12-08 15:05:18 Using 4 threads for script verification
2016-12-08 15:05:18 scheduler thread start
2016-12-08 15:05:18 Binding RPC on address 0.0.0.0 port 8332 failed.
2016-12-08 15:05:18 HTTP: creating work queue of depth 16
2016-12-08 15:05:18 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
2016-12-08 15:05:18 HTTP: starting 4 worker threads
2016-12-08 15:05:18 Using wallet wallet.dat
2016-12-08 15:05:18 init message: Verifying wallet...
2016-12-08 15:05:18 CDBEnv::Open: LogDir=/mynode/data/database ErrorFile=/mynode/data/db.log
2016-12-08 15:05:18 Bound to [::]:8333
2016-12-08 15:05:18 Bound to 0.0.0.0:8333
2016-12-08 15:05:18 Block index database configuration:
2016-12-08 15:05:18 * Using 1000 max open files
2016-12-08 15:05:18 * Compression is enabled
2016-12-08 15:05:18 Cache configuration:
2016-12-08 15:05:18 * Max cache setting possible 16384MiB
2016-12-08 15:05:18 * Using 75.0MiB for block index database
2016-12-08 15:05:18 * Using 12.5MiB for chain state database
2016-12-08 15:05:18 * Using 12.5MiB for in-memory UTXO set
2016-12-08 15:05:18 init message: Loading block index...
2016-12-08 15:05:18 Opening LevelDB in /mynode/data/blocks/index
2016-12-08 15:05:19 Opened LevelDB successfully
2016-12-08 15:05:19 Using obfuscation key for /mynode/data/blocks/index: 0000000000000000
2016-12-08 15:05:19 Opening LevelDB in /mynode/data/chainstate
2016-12-08 15:05:19 Opened LevelDB successfully
2016-12-08 15:05:19 Using obfuscation key for /mynode/data/chainstate: 987af5ef38f6c6f0
2016-12-08 15:05:24 LoadBlockIndexDB: last block file = 592
2016-12-08 15:05:24 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=115, size=88605372, heights=423305...424335, time=2016-08-02...2016-08-08)
2016-12-08 15:05:24 Checking all blk files are present...
2016-12-08 15:05:24 LoadBlockIndexDB: transaction index enabled
2016-12-08 15:05:24 LoadBlockIndexDB: address index enabled
2016-12-08 15:05:24 LoadBlockIndexDB: timestamp index enabled
2016-12-08 15:05:24 LoadBlockIndexDB: spent index enabled
2016-12-08 15:05:25 LoadBlockIndexDB: hashBestChain=0000000000000000044044f4beb1f7a86eaca2be599ffde7f004d7fe1542e2aa height=423569 date=2016-08-04 01:34:08 progress=0.939347
2016-12-08 15:05:25 init message: Verifying blocks...
2016-12-08 15:05:25 Verifying last 288 blocks at level 3
2016-12-08 15:06:29 No coin database inconsistencies in last 3 blocks (5213 transactions)
2016-12-08 15:06:29  block index           70643ms
2016-12-08 15:06:29 init message: Loading wallet...
2016-12-08 15:06:29 nFileVersion = 120100
2016-12-08 15:06:29 Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
2016-12-08 15:06:29  wallet                  173ms
2016-12-08 15:06:29 init message: Activating best chain...
2016-12-08 15:07:28 UpdateTip: new best=000000000000000004c4ea0004df513c5e2e57a8636bf767c3782327eea7883c  height=423570  log2_work=85.081446  tx=146844994  date=2016-08-04 01:50:07 progress=0.939352  cache=0.1MiB(0tx)
2016-12-08 15:08:05 Pre-allocating up to position 0x200000 in rev00589.dat
2016-12-08 15:08:05 UpdateTip: new best=000000000000000003bf36ce15d4791e95026b87ec945d14b09b6ac5b25e0aff  height=423571  log2_work=85.081477  tx=146845078  date=2016-08-04 01:50:33 progress=0.939352  cache=3.2MiB(2347tx)
2016-12-08 15:08:57 UpdateTip: new best=0000000000000000019b653562ee66f4f34633e71a2738f05ec53ed5c37ad296  height=423572  log2_work=85.081507  tx=146845242  date=2016-08-04 01:51:06 progress=0.939352  cache=9.2MiB(5557tx)
2016-12-08 15:09:17 UpdateTip: new best=000000000000000004a8fdb2df1a22065296729d48f54c1b306ba0ceb4a47fd8  height=423573  log2_work=85.081538  tx=146847946  date=2016-08-04 02:18:21 progress=0.939362  cache=0.1MiB(0tx)
2016-12-08 15:09:32 UpdateTip: new best=000000000000000000a45624047cfb24d80db48277d072725c1b136e5c48df00  height=423574  log2_work=85.081569  tx=146850475  date=2016-08-04 02:52:44 progress=0.939374  cache=7.1MiB(6361tx)
2016-12-08 15:09:53 UpdateTip: new best=000000000000000002ccaf699cfefe39d2b49754c53d38af0f06d98837e67916  height=423575  log2_work=85.081599  tx=146852788  date=2016-08-04 02:56:32 progress=0.939376  cache=0.1MiB(0tx)
2016-12-08 15:10:01 UpdateTip: new best=000000000000000002ff96101dd3411c79a67b146aa026bfaddcf80c21295813  height=423576  log2_work=85.08163  tx=146854768  date=2016-08-04 03:08:14 progress=0.939381  cache=11.4MiB(5417tx)
2016-12-08 15:10:04 UpdateTip: new best=0000000000000000047c31e8ce7528c152c0a05554b9070b5f98085b13a095a8  height=423577  log2_work=85.08166  tx=146855448  date=2016-08-04 03:31:03 progress=0.939388  cache=11.7MiB(6582tx)
2016-12-08 15:10:25 UpdateTip: new best=000000000000000001afd3e04c645adfca5e0ec9c817ba4b5d00841a7a348cb5  height=423578  log2_work=85.081691  tx=146856799  date=2016-08-04 03:37:41 progress=0.939391  cache=0.1MiB(0tx)
2016-12-08 15:10:25 mapBlockIndex.size() = 442456
2016-12-08 15:10:25 nBestHeight = 423578
2016-12-08 15:10:25 setKeyPool.size() = 101
2016-12-08 15:10:25 mapWallet.size() = 0
2016-12-08 15:10:25 mapAddressBook.size() = 1
2016-12-08 15:10:25 init message: Loading addresses...
2016-12-08 15:10:25 ERROR: Read: Failed to open file /mynode/data/peers.dat
2016-12-08 15:10:25 Invalid or missing peers.dat; recreating
2016-12-08 15:10:25 ERROR: Read: Failed to open file /mynode/data/banlist.dat
2016-12-08 15:10:25 torcontrol thread start
2016-12-08 15:10:25 Invalid or missing banlist.dat; recreating
2016-12-08 15:10:25 Loaded 0 addresses from peers.dat  0ms
2016-12-08 15:10:25 dnsseed thread start
2016-12-08 15:10:25 Loading addresses from DNS seeds (could take a while)
2016-12-08 15:10:25 addcon thread start
2016-12-08 15:10:25 net thread start
2016-12-08 15:10:25 opencon thread start
2016-12-08 15:10:25 msghand thread start
2016-12-08 15:10:25 init message: Done loading
2016-12-08 15:10:25 receive version message: /bitcoin-seeder:0.01/: version 60000, blocks=350000, us=88.191.53.22:8333, peer=1
2016-12-08 15:10:25 tor: Thread interrupt
2016-12-08 15:10:25 torcontrol thread exit
2016-12-08 15:10:25 Shutdown: In progress...
2016-12-08 15:10:25 scheduler thread interrupt
2016-12-08 15:10:25 opencon thread interrupt
2016-12-08 15:10:25 addcon thread interrupt
2016-12-08 15:10:25 msghand thread interrupt
2016-12-08 15:10:25 net thread interrupt
2016-12-08 15:10:25 dnsseed thread interrupt
2016-12-08 15:10:25 StopNode()
2016-12-08 15:10:26 Shutdown: done
```

**Comment by jerrymg** [comment]
I am getting the same error on a fresh ubuntu 16.04 LTS install. It happened when Insight UI showed about 88% synced.

**Comment by awsashish** [comment]
Any Luck ???? I am facing the same issue....

**Comment by msapelov** [comment]
May be try to add more SWAP ?

**Comment by m19** [comment]
I have the same issue on Ubuntu 16.04 on Digital Ocean with a 250GB block space.

Stuck around 80%.

**Comment by msapelov** [comment]
> I have the same issue on Ubuntu 16.04 on Digital Ocean with a 250GB block space.
`free -m` Check that you have enough RAM and/or SWAP.

**Comment by m19** [comment]
Fixed it by upgrading from 2GB RAM to 4GB

**Comment by winteraz** [comment]
I get the same error when I add multiple nodes (addnode=x.x.x.x.) in bitcoin.conf. I have plenty of RAM (64GB )

**Comment by Lalitpatadiya12** [comment]
Any Luck ???? I am facing the same issue....

**Comment by Duanthse03268** [comment]
i'm facing same issue

**Comment by DaShak** [comment]
I am currently working on resolving a similar [if not same] issue.

In the process, I found another thread with a potential solution:
https://github.com/bitpay/bitcore-node/issues/498
