### ISSUE TITLE
failed to start service, unknown network

### ISSUE THREAD

**Issue by UsamaMehboob** [bitpay/bitcore#1461]
Hi, I have installed bitcore daemon but whenever I run the command "bitcored", I get unable to start services,
Here is the log:

---
Bitcoin Height: 722175 Percentage: 98.48
[2017-07-03T03:07:05.700Z] info: Bitcoin Daemon Ready
[2017-07-03T03:07:05.701Z] info: Starting web
[2017-07-03T03:07:05.819Z] info: Starting insight-api
[2017-07-03T03:07:05.820Z] info: Starting bitcore-wallet-service
[2017-07-03T03:07:05.822Z] error: Failed to start services
[2017-07-03T03:07:05.823Z] error: Error: Unknown network
    at Service._getConfiguration (/home/osboxes/Documents/testnode/node_modules/bitcore-wallet-service/bitcorenode/index.js:99:11)
    at Service.start (/home/osboxes/Documents/testnode/node_modules/bitcore-wallet-service/bitcorenode/index.js:136:19)
    at Node._startService (/home/osboxes/Documents/testnode/node_modules/bitcore-node/lib/node.js:205:11)
    at /home/osboxes/Documents/testnode/node_modules/bitcore-node/lib/node.js:260:12
    at /home/osboxes/Documents/testnode/node_modules/bitcore-node/node_modules/async/lib/async.js:181:20
    at iterate (/home/osboxes/Documents/testnode/node_modules/bitcore-node/node_modules/async/lib/async.js:262:13)
    at /home/osboxes/Documents/testnode/node_modules/bitcore-node/node_modules/async/lib/async.js:274:29
    at /home/osboxes/Documents/testnode/node_modules/bitcore-node/node_modules/async/lib/async.js:44:16
    at Immediate._onImmediate (/home/osboxes/Documents/testnode/node_modules/bitcore-node/lib/node.js:233:5)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
[2017-07-03T03:07:05.827Z] info: Beginning shutdown
[2017-07-03T03:07:05.828Z] info: Stopping insight-ui (not started)
[2017-07-03T03:07:05.829Z] info: Stopping bitcore-wallet-service
[2017-07-03T03:07:05.829Z] info: Stopping insight-api
[2017-07-03T03:07:05.830Z] info: Stopping web
[2017-07-03T03:07:05.831Z] info: Stopping bitcoind
[2017-07-03T03:07:06.168Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2017-07-03T03:07:06.169Z] info: ZMQ connected to: tcp://127.0.0.1:28332
[2017-07-03T03:07:09.173Z] warn: ZMQ disconnect: tcp://127.0.0.1:28332
[2017-07-03T03:07:09.174Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2017-07-03T03:07:09.174Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332

**Comment by ccMehdi** [comment]
Hey,

Were you able to get it up and running? Running into the same issue. 

Regards

**Comment by UsamaMehboob** [comment]
No, I could not get it to running, if you find a solution, please let me know. thanks

**Comment by psarchi** [comment]
not found any solutions yet, i have same issue. 

in Index.js Line 99 is giving the error, its network related , it cant read testnet/livenet from config. trying to find where the config error is.

**Comment by ccMehdi** [comment]
We got it up and running. Change the code for the following from line 90 to 100
`if (self.node.network.name === Networks.livenet.name) {
    baseConfig.blockchainExplorerOpts = {
      livenet: providerOptions
    };
  } else if (self.node.network.name === Networks.testnet.name) {
    baseConfig.blockchainExplorerOpts = {
      testnet: providerOptions
    };
  } else {
    throw new Error('Unknown network');
  }`

Let me know if you are having any issues with block syncing.

**Comment by psarchi** [comment]
I think it fixed it. Thank you.

**Comment by Smurfy303** [comment]
Hi, I am facing issue it not throwing me an issue but for data sync.
I am tried for livenet, you can see as below,

> admin1@admin1-desktop:~/Desktop/bitcoin_demo$ bitcored
> [2018-04-14T11:31:05.947Z] info: Using config: /home/admin1/.bitcore/bitcore-node.json
> [2018-04-14T11:31:05.949Z] info: Using network: livenet
> [2018-04-14T11:31:05.950Z] info: Starting bitcoind
> [2018-04-14T11:31:05.952Z] info: Using bitcoin config file: /home/admin1/.bitcore/data/bitcoin.conf
> [2018-04-14T11:31:05.954Z] info: Starting bitcoin process
> ### **[2018-04-14T11:31:10.992Z] info: Bitcoin Height: 0 Percentage: 0.00**
> [2018-04-14T11:31:10.996Z] info: Bitcoin Daemon Ready
> [2018-04-14T11:31:10.997Z] info: Starting web
> [2018-04-14T11:31:11.013Z] info: Starting insight-api
> [2018-04-14T11:31:11.013Z] info: Starting insight-ui
> [2018-04-14T11:31:11.014Z] info: Bitcore Node ready
> [2018-04-14T11:31:11.484Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
> [2018-04-14T11:31:11.485Z] info: ZMQ connected to: tcp://127.0.0.1:28332
> 

How to sync bitcoin with livenet ??
