### ISSUE TITLE
Bitcore server not starting after installing bitcore-wallet-service 

### ISSUE THREAD

**Issue by xishoon** [bitpay/bitcore#1480]
Hi,

I have installed bitcore-beta version, than i successfully installed insight-api beta as well. Till that point my node was starting as expected (i.e $ bitcored), But when i installed bitcore-wallet-service  under my new  node directory like this
   $  cd my-new-node
   $ npm install insight-api@beta
   $ npm install insight-ui@beta
   $ bitcore install bitcore-wallet-service

after this when i run  $ bitcored, it starts throwing following error.

Any thoughts?

[2017-10-10T17:56:00.687Z] info: Checked the current working directory for service: mempool
[2017-10-10T17:56:00.757Z] info: Checked the current working directory for service: address
[2017-10-10T17:56:00.762Z] info: Checked the current working directory for service: bitcore-wallet-service
[2017-10-10T17:56:00.763Z] info: Checked the built-in path: lib/services, for service: bitcore-wallet-service

**[2017-10-10T17:56:01.369Z] error: uncaught exception: { AssertionError [ERR_ASSERTION]: Required dependency "insight-api" not available.**
    at addToStack (/home/zeshan/amaano-beta/node_modules/bitcore-node/lib/node.js:100:7)
    at addToStack (/home/zeshan/amaano-beta/node_modules/bitcore-node/lib/node.js:102:7)
    at Node._getServiceOrder (/home/zeshan/amaano-beta/node_modules/bitcore-node/lib/node.js:112:3)
    at Node.start (/home/zeshan/amaano-beta/node_modules/bitcore-node/lib/node.js:183:28)
    at start (/home/zeshan/amaano-beta/node_modules/bitcore-node/lib/scaffold/start.js:40:8)
    at Object.main [as daemon] (/home/zeshan/amaano-beta/node_modules/bitcore-node/lib/cli/daemon.js:34:3)
    at Liftoff.<anonymous> (/home/zeshan/.nvm/versions/node/v8.3.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/cli/bitcored.js:29:16)
    at Liftoff.<anonymous> (/home/zeshan/.nvm/versions/node/v8.3.0/lib/node_modules/bitcore/node_modules/liftoff/index.js:202:12)
    at Liftoff.<anonymous> (/home/zeshan
eshan/.nvm/versions/node/v8.3.0/lib/node_modules/bitcore/node_modules/liftoff/index.js:169:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' }
[2017-10-10T17:56:01.371Z] error: AssertionError [ERR_ASSERTION]: Required dependency "insight-api" not available.

**Comment by Lalitpatadiya12** [comment]
@xishoon  kindly provide the version of node,npm and nvm.

**Comment by xishoon** [comment]
@Lalitpatadiya12 my node version is 8.6.0, npm version is 5.3.0 and nvm version is 0.33.5
