### ISSUE TITLE
More than one instance of bitcore-lib found

### ISSUE THREAD

**Issue by askucher** [bitpay/bitcore#1484]
```
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/var/www/bs-snov2/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/var/www/bs-snov2/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/bs-snov2/app.js:19:13)
```

**Comment by fanatid** [comment]
"okay github, versionguard issues"
https://github.com/bitpay/bitcore/search?q=versionGuard&type=Issues&utf8=%E2%9C%93
https://github.com/bitpay/bitcore-lib/search?q=versionGuard&type=Issues&utf8=%E2%9C%93

**Comment by pabx06** [comment]
same issue

**Comment by adiingit** [comment]
Follow this !!
https://github.com/bitpay/bitcore/issues/1457#issuecomment-467594031
