### ISSUE TITLE
Issue with the ZMQ while running bitcored : Monitoring support disabled check zmq version is > 3.2.1 and recompile this addon

### ISSUE THREAD

**Issue by blockstein** [bitpay/bitcore#1485]
Hi, We are having this issue and not sure what is the method to resolve . Any help will be much appreciated.

 vishal@ubuntu:~$ bitcored
[2017-12-07T15:11:30.033Z] info: Using config: /home/vishal/.bitcore/bitcore-node.json
[2017-12-07T15:11:30.034Z] info: Using network: livenet
[2017-12-07T15:11:30.035Z] info: Starting bitcoind
[2017-12-07T15:11:30.037Z] info: Using bitcoin config file: /home/vishal/.bitcore/data/bitcoin.conf
[2017-12-07T15:11:30.039Z] info: Starting bitcoin process
[2017-12-07T15:11:35.114Z] error: uncaught exception: [Error: Monitoring support disabled check zmq version is > 3.2.1 and recompile this addon]
[2017-12-07T15:11:35.117Z] error: Error: Monitoring support disabled check zmq version is > 3.2.1 and recompile this addon
    at Socket.monitor (/home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/zmq/lib/index.js:543:11)
    at Bitcoin._initZmqSubSocket (/home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:742:21)
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:908:12
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:676:51
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:726:13
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:52:16
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:264:21
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:44:16
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:723:17
    at /home/vishal/.nvm/versions/node/v4.5.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:167:37
[2017-12-07T15:11:35.118Z] info: Beginning shutdown
[2017-12-07T15:11:35.119Z] info: Stopping insight-ui (not started)
[2017-12-07T15:11:35.119Z] info: Stopping insight-api (not started)
[2017-12-07T15:11:35.120Z] info: Stopping web (not started)
[2017-12-07T15:11:35.120Z] info: Stopping bitcoind
![capture](https://user-images.githubusercontent.com/34345859/33722999-730fd740-db91-11e7-8fa9-5e8a3ae3c1ae.JPG)

**Comment by qdztxc** [comment]
Hello blockstein.

I encountered same issue. How did you solve this issue?

**Comment by qdztxc** [comment]
@blockstein

**Comment by TivonChen** [comment]
same problem, any help?

**Comment by TivonChen** [comment]
ok, I solved this problem by following there steps: https://gist.github.com/katopz/8b766a5cb0ca96c816658e9407e83d00, hope it can help u!

**Comment by gicucorcodel** [comment]
for me work sudo apt-get install libzmq3-dev
