### ISSUE TITLE
More than one instance of bitcore-lib found

### ISSUE THREAD

**Issue by bibz0r** [bitpay/bitcore#1486]
Getting this error: 

am@debianBlock:~$ bitcored
/home/am/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/am/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/am/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/am/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/insight-api/lib/blocks.js:4:15)
    at Module._compile (module.js:409:26)

What to do?

**Comment by tumaponchard16** [comment]
Same issue here!

**Comment by pabx06** [comment]
yup me too
