### ISSUE TITLE
Fail to install module

### ISSUE THREAD

**Issue by EasonWang01** [bitpay/bitcore#1495]
```
Node.js version: 8.9.0
OS: macOS
```

```
npm install bitcore
```
```
Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-4/bitcoin-0.12.1-osx64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    326      0 --:--:--  0:00:01 --:--:--   326
100 18.8M  100 18.8M    0     0   224k      0  0:01:25  0:01:25 --:--:--  263k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   604    0   604    0     0    198      0 --:--:--  0:00:03 --:--:--   199
100  1154  100  1154    0     0    232      0  0:00:04  0:00:04 --:--:--   857
Unpacking bitcoin distribution
x bitcoin-0.12.1/
x bitcoin-0.12.1/bin/
x bitcoin-0.12.1/bin/bitcoin-cli
x bitcoin-0.12.1/bin/bitcoind
x bitcoin-0.12.1/bin/bitcoin-qt
x bitcoin-0.12.1/bin/bitcoin-tx
x bitcoin-0.12.1/bin/test_bitcoin
x bitcoin-0.12.1/bin/wallet-utility
x bitcoin-0.12.1/include/
x bitcoin-0.12.1/include/bitcoinconsensus.h
x bitcoin-0.12.1/lib/
x bitcoin-0.12.1/lib/libbitcoinconsensus.0.dylib
x bitcoin-0.12.1/lib/libbitcoinconsensus.dylib

> zmq@2.15.3 install /Users/lin/test/node_modules/zmq
> node-gyp rebuild

Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lin/test/node_modules/zmq
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmq@2.15.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by ilovelinux** [comment]
You have to install it. If you are using Ubuntu, run this command:
`sudo apt install libczmq`
and retry to install Bitcore

If it raise the same error, try with
`sudo apt install libczmq3`

**Comment by EasonWang01** [comment]
thanks
