### ISSUE TITLE
bitcored running daemon end up with error

### ISSUE THREAD

**Issue by goodthebest** [bitpay/bitcore#1506]
I'm trying to install bitcore node on ubuntu 16.04
everything went smooth however when I run 
`bitcored`

it's giving following error, any fix?
---------------------------
>[error] (node) listen EADDRINUSE 127.0.0.1:8332
[error] (node) listen EADDRINUSE 127.0.0.1:8332
(node:19209) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE 127.0.0.1:8332
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:19209) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19209) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----------------------------------

**Comment by goodthebest** [comment]
port was already in use. I killed the process and it worked.
