### ISSUE TITLE
running bitcored broken - install steps from guide

### ISSUE THREAD

**Issue by miketwenty1** [bitpay/bitcore#1510]
Provisioning a brand new node I'm not running into this problem when launching "bitcored"
https://bitcore.io/guides/full-node -> Guide I'm following

``
bitcore@bitcore:~$ bitcored
/home/bitcore/.nvm/versions/node/v4.9.0/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/bitcore/.nvm/versions/node/v4.9.0/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/bitcore/.nvm/versions/node/v4.9.0/lib/node_modules/bitcore/node_modules/insight-api/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bitcore/.nvm/versions/node/v4.9.0/lib/node_modules/bitcore/node_modules/insight-api/lib/blocks.js:4:15)
    at Module._compile (module.js:409:26)
``

**Comment by killswitch-GUI** [comment]
@giancarlopetrini is using a version from 2016 really the fix for this?

**Comment by osagga** [comment]
@killswitch-GUI just use bitcore-v8 from the `v8.0.0` branch on this repo

**Comment by killswitch-GUI** [comment]
ok rgr ty!
