### ISSUE TITLE
Make bitcore-node faster

### ISSUE THREAD

**Issue by micahriggan** [bitpay/bitcore#1596]
Currently the addBlock function is too slow. There are many factors that contribute to this.

Most of the time comes from mongo.

```
MONGO_TIME = 2x "CoinModel::collection.bulkWrite" +  "TransactionModel::collection.bulkWrite"
MONGO_TIME = 2*1486ms + 482ms = 3454ms
```

3.4 seconds per block is MONGO_TIME
.300 seconds "TransactionSchema::getMintOps"
.178 seconds "TransactionSchema::addTransactions"

TOTAL = 4.383 seconds / Block
```
{
   
    "BlockSchema::getLocalTip": {
        "time": 164,
        "count": 42,
        "avg": 3.9047619047619047
    },
    "BlockSchema::handleReorg": {
        "time": 13333,
        "count": 39,
        "avg": 341.87179487179486
    },
    "BlockSchema::getLocatorHashes": {
        "time": 18,
        "count": 2,
        "avg": 9
    },
    "BtcP2pService::getMissingBlockHashes": {
        "time": 233,
        "count": 2,
        "avg": 116.5
    },
    "BtcP2pService::getBlock": {
        "time": 218121,
        "count": 47,
        "avg": 4640.872340425532
    },
    "P2pRunner::getBlock": {
        "time": 1832,
        "count": 36,
        "avg": 50.888888888888886
    },
    "TransactionSchema::getMintOps": {
        "time": 12003,
        "count": 36,
        "avg": 333.4166666666667
    },
    "CoinModel::collection.bulkWrite": {
        "time": 3215847,
        "count": 2164,
        "avg": 1486.0660813308687
    },
    "TransactionSchema::getSpendOps": {
        "time": 955,
        "count": 36,
        "avg": 26.52777777777778
    },
    "TransactionSchema::addTransactions": {
        "time": 6239,
        "count": 35,
        "avg": 178.25714285714287
    },
    "TransactionModel::collection.bulkWrite": {
        "time": 191092,
        "count": 396,
        "avg": 482.55555555555554
    },
    "TransactionSchema::batchImport": {
        "time": 151238,
        "count": 35,
        "avg": 4321.085714285714
    },
    "BlockSchema::addBlock": {
        "time": 153406,
        "count": 35,
        "avg": 4383.028571428571
    }
}
```

**Comment by enewhuis** [comment]
Has there been any progress on this?  I've got over 10,000 IOPS running at Amazon trying to crunch through this and it is taking dayeeeeezzzzzzzz........

**Comment by micahriggan** [comment]
Is that with the master branch? That sounds about right, we've had a few changes recently that were negative on performance, but made sync idempotent. I would expect 5-6 days for sync time, is that in-line with what you're experiencing?

**Comment by enewhuis** [comment]
Feels like it; almost there.  Also while figuring this out I've had to deal with the equations of Amazon motion on both volume- and instance-specific IOPS.  For those at Amazon my current recommendation is an m5.2xlarge with an io1 SSD volume of 512GB plus 12000 reserved IOPS or something equivalent.  One must check the baseline IOPS for the instance otherwise you will wind up paying for IOPS you cannot use.

**Comment by lutsifer** [comment]
Hello there,
Since I had the same problem with mongo sync speed I decided to give it a try to master branch improvements and I hit a snag:)

I'm using Ubuntu 16.04. The v8 branch works just fine (at least it was two days ago).

I was not sure about the node version I was suppose to use (I tried with v8 and latest - same result):

```
lerna ERR! npm run compile stderr:
sh: 1: ./node_modules/.bin/tsc: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bitcore-node@8.0.1 tsc: `npm run clean && ./node_modules/.bin/tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bitcore-node@8.0.1 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stefan/.npm/_logs/2019-02-22T12_46_42_461Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.0.1 compile: `npm run tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@8.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stefan/.npm/_logs/2019-02-22T12_46_42_477Z-debug.log

lerna ERR! npm run compile exited 1 in 'bitcore-node'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 compile: `lerna run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stefan/.npm/_logs/2019-02-22T12_46_42_501Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 postinstall: `npm run bootstrap && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

Not sure what is wrong...

**Comment by micahriggan** [comment]
This would indicate that typescript is not installed in the bitcore-node directory. I'll check our package.json file, but make sure you've done an npm install from the root bitcore directory

**Comment by lutsifer** [comment]
Great, npm install works after manually installing typescript in bitcore-node, however when I run it I get this:
```
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/stefan/Desktop/bitc/packages/bitcore-node/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.0.1 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@8.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stefan/.npm/_logs/2019-02-22T14_48_53_571Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.0.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Comment by micahriggan** [comment]
Interesting, that would mean that scrypt isn't installed. I believe I have that globally installed. Try npm install scrypt in bitcore-node and see if that fixes it

You may have some issues with your C compiling toolchain, which would result in scrypt failing to build

**Comment by lutsifer** [comment]
> Try npm install scrypt in bitcore-node and see if that fixes it

That is what I did in a first place. 

> You may have some issues with your C compiling toolchain, which would result in scrypt failing to build

If that was the case, then how am I runing  v8 branch from the repo?

**Comment by micahriggan** [comment]
Hmm, when you were running v8, were you on the same node.js version that you're on now?

could you post your node -v and npm -v and I'll give it a shot with the same as you

**Comment by lutsifer** [comment]
Unfortunately - absolutely same version of node and npm :)
node
v8.11.4
npm
5.6.0

**Comment by enewhuis** [comment]
BTW I am now using 18,750 IOPS on 1TB SSD on an m5.12xlarge instance.  ~$3/hour

With this setup at Amazon I have a reasonable initial sync rate.  In a few hours, I will bump that to 40,000 IOPS for the final stretch.

**Comment by lutsifer** [comment]
Is there a way to store bitcore mongdb collection in order to speed up this initial sync? Same way like bitcoin database is stored on some servers? I am trying to synchronize already second day and I am barely at 310k height. I bet it will take another 2 3 days to finish up the process..

**Comment by enewhuis** [comment]
$ mongo> show dbs
admin      0.000GB
bitcore  383.038GB
bws        0.003GB
config     0.000GB
local      0.000GB
>

**Comment by lutsifer** [comment]
Perhaps if we create tar.xz from this collection files size might be more... manageable and we can distribute a torrent file? It will make sense to keep mongodb copy for emergencies?

**Comment by enewhuis** [comment]
Is the Mongo bitcore structure stable?  Is there a schema version or some way to know compatibility?

**Comment by lutsifer** [comment]
@enewhuis good question, does the regular mongoexport/import work here?
https://docs.mongodb.com/manual/reference/program/mongoexport/#bin.mongoexport

Obviously mongodump is not going to work here because of the size..

**Comment by lutsifer** [comment]
@micahriggan today I was able to run the master branch, indeed it is faster

**Comment by KiriKiri** [comment]
Hello, can somebody share the mongodb database of synced testnet and mainnet? Maybe using torrent, or I can give access to the dropbox?
