### ISSUE TITLE
wallet-create does not work if wallet.config.json doesn't exist,

### ISSUE THREAD

**Issue by nitsujlangston** [bitpay/bitcore#1620]
stack:
```
TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.save (/home/justin/repos/bitcore/packages/bitcore-client/lib/config.js:34:10)
    at Object.addWallet (/home/justin/repos/bitcore/packages/bitcore-client/lib/config.js:41:12)
    at Function.create (/home/justin/repos/bitcore/packages/bitcore-client/lib/wallet.js:65:12)
    at <anonymous>
```

Wallet config should be created if it doesn't exist, should probably change the default path to `~/.bitcore-wallet.config.json`, in keeping with tradtional app specific configs in home directory. May even make sense to put in it's own directory `.bitcore`, etc.

**Comment by nitsujlangston** [comment]
resolved
