### ISSUE TITLE
it should not be happened at all - how to fix it?

### ISSUE THREAD

**Issue by askucher** [bitpay/bitcore#1748]
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/var/www/ethnamed/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/var/www/ethnamed/node_modules/bitcore-lib/index.js:15:9)

**Comment by fanatid** [comment]
https://github.com/bitpay/bitcore/issues?utf8=%E2%9C%93&q=More+than+one+instance
