### ISSUE TITLE
v8: Unhandled rejection at: TypeError: Cannot read property 'syncingNode:BTC:mainnet' of null

### ISSUE THREAD

**Issue by jamespharvey20** [bitpay/bitcore#1865]
No idea if this matters, but in the spirit of beta testing, after completing a bitcoin core `0.16.3` initial sync, cloning git d5ce6fa0, running `npm install` and `npm start`, I got the following error.  It's continued on, and up to syncing a height of about 50k so far.

```
...
info: Starting Socket Service
info: Starting P2P Manager
info: Connected to peer 127.0.0.1 chain=BTC, network=mainnet
Unhandled Rejection at: TypeError: Cannot read property 'syncingNode:BTC:mainnet' of null                                                                               
    at StateModel.getSyncingNode (/home/bitcore/bitcore.git/packages/bitcore-node/build/src/models/state.js:20:27)                                                      
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
info: This worker is now the syncing node for BTC mainnet
info: Syncing 2000 blocks for BTC mainnet
info: Sync  chain=BTC, network=mainnet, height=1
info: Sync  chain=BTC, network=mainnet, height=5
...
```

**Comment by micahriggan** [comment]
Thanks for the report!

**Comment by micahriggan** [comment]
@nitsujlangston https://github.com/bitpay/bitcore/blob/ea0bc2cc36a86f1082e59e94ba83f584dde56617/packages/bitcore-node/src/models/state.ts#L23

Shouldn't this have the mongo option 
```
returnNewDocument: true
```

**Comment by micahriggan** [comment]
Seems Node.js native driver uses 
```
23       { returnOriginal: false }
```
