### ISSUE TITLE
Can't start bitcoind anymore

### ISSUE THREAD

**Issue by mvcastellari** [bitpay/bitcore#1989]
I was using bitcored for about a month, today i got out of disk space and needed to restart the machine, now i can't start bitcoind anymore, i got the following error:

[2019-02-13T16:19:50.032Z] info: Using bitcoin config file: /mnt/volume_nyc3_01/data/bitcoin.conf
[2019-02-13T16:19:50.042Z] warn: Stopping existing spawned bitcoin process with pid: 10021
[2019-02-13T16:19:50.042Z] warn: Unclean bitcoin process shutdown, process not found with pid: 10021
[2019-02-13T16:19:50.042Z] info: Starting bitcoin process
[2019-02-13T16:19:55.031Z] warn: Loading block index...
[2019-02-13T16:19:55.055Z] warn: Loading block index...
[2019-02-13T16:20:00.038Z] warn: Loading block index...
[2019-02-13T16:20:00.057Z] warn: Loading block index...
[2019-02-13T16:20:05.044Z] warn: Loading block index...
[2019-02-13T16:20:05.059Z] warn: Loading block index...
[2019-02-13T16:20:10.049Z] warn: Loading block index...
[2019-02-13T16:20:10.063Z] warn: Loading block index...
[2019-02-13T16:20:15.058Z] warn: Loading block index...
[2019-02-13T16:20:15.065Z] warn: Loading block index...
[2019-02-13T16:20:20.068Z] warn: Loading block index...
[2019-02-13T16:20:20.070Z] warn: Loading block index...
[2019-02-13T16:20:25.074Z] warn: Loading block index...
[2019-02-13T16:20:25.075Z] warn: Loading block index...
[2019-02-13T16:20:30.080Z] warn: Loading block index...
[2019-02-13T16:20:30.081Z] warn: Loading block index...
[2019-02-13T16:20:35.083Z] warn: Loading block index...
[2019-02-13T16:20:35.085Z] warn: Loading block index...
[2019-02-13T16:20:40.088Z] warn: Loading block index...
[2019-02-13T16:20:40.088Z] warn: Loading block index...
[2019-02-13T16:20:45.094Z] warn: Loading block index...
[2019-02-13T16:20:45.095Z] warn: Loading block index...
[2019-02-13T16:20:50.102Z] warn: Loading block index...
[2019-02-13T16:20:50.102Z] warn: Loading block index...
[2019-02-13T16:20:55.108Z] warn: Loading block index...
[2019-02-13T16:20:55.108Z] warn: Loading block index...
[2019-02-13T16:21:00.116Z] warn: Loading block index...
[2019-02-13T16:21:00.116Z] warn: Loading block index...
[2019-02-13T16:21:05.119Z] warn: Loading block index...
[2019-02-13T16:21:05.120Z] warn: Loading block index...
[2019-02-13T16:21:10.123Z] warn: Loading block index...
[2019-02-13T16:21:10.127Z] warn: Loading block index...
[2019-02-13T16:21:15.136Z] warn: Loading block index...
[2019-02-13T16:21:15.137Z] warn: Loading block index...
[2019-02-13T16:21:20.144Z] warn: Loading block index...
[2019-02-13T16:21:20.146Z] warn: Loading block index...
[2019-02-13T16:21:25.156Z] warn: Loading block index...
[2019-02-13T16:21:25.159Z] warn: Loading block index...
[2019-02-13T16:21:30.158Z] warn: Loading block index...
[2019-02-13T16:21:30.161Z] warn: Loading block index...
[2019-02-13T16:21:35.166Z] warn: Loading block index...
[2019-02-13T16:21:35.167Z] warn: Loading block index...
[2019-02-13T16:21:40.170Z] warn: Loading block index...
[2019-02-13T16:21:40.171Z] warn: Loading block index...
[2019-02-13T16:21:45.173Z] warn: Loading block index...
[2019-02-13T16:21:45.174Z] warn: Loading block index...
[2019-02-13T16:21:50.178Z] warn: Loading block index...
[2019-02-13T16:21:50.179Z] warn: Loading block index...
[2019-02-13T16:21:55.182Z] warn: Loading block index...
[2019-02-13T16:21:55.182Z] warn: Loading block index...
[2019-02-13T16:22:00.189Z] warn: Loading block index...
[2019-02-13T16:22:00.190Z] warn: Loading block index...
[2019-02-13T16:22:10.997Z] warn: Loading block index...
[2019-02-13T16:22:11.009Z] warn: Bitcoin process unexpectedly exited with code: null
[2019-02-13T16:22:11.009Z] warn: Restarting bitcoin child process in 5000ms
[2019-02-13T16:22:16.009Z] info: Using bitcoin config file: /mnt/volume_nyc3_01/data/bitcoin.conf
[2019-02-13T16:22:16.019Z] warn: Stopping existing spawned bitcoin process with pid: 10196
[2019-02-13T16:22:16.019Z] warn: Unclean bitcoin process shutdown, process not found with pid: 10196
[2019-02-13T16:22:16.019Z] info: Starting bitcoin process
[2019-02-13T16:22:21.016Z] warn: Loading block index...
[2019-02-13T16:22:21.025Z] warn: Loading block index...
[2019-02-13T16:22:21.037Z] warn: Loading block index...
[2019-02-13T16:22:26.022Z] warn: Loading block index...
[2019-02-13T16:22:26.027Z] warn: Loading block index...
[2019-02-13T16:22:26.040Z] warn: Loading block index...
[2019-02-13T16:22:31.029Z] warn: Loading block index...
[2019-02-13T16:22:31.031Z] error: Failed to start services
[2019-02-13T16:22:31.032Z] error: RPCError: Loading block index...
    at Bitcoin._wrapRPCError (/root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:449:13)
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:779:28
    at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:107:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
[2019-02-13T16:22:31.032Z] info: Beginning shutdown
[2019-02-13T16:22:31.033Z] info: Stopping bitcoind
[2019-02-13T16:22:31.034Z] warn: Loading block index...
[2019-02-13T16:22:31.041Z] error: Error: Stopping while trying to spawn bitcoind.
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:905:25
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:676:51
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:726:13
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:52:16
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:264:21
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:44:16
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:723:17
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:167:37
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:652:25
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:887:16
[2019-02-13T16:22:36.040Z] error: Error: Stopping while trying to spawn bitcoind.
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:905:25
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:676:51
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:726:13
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:52:16
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:264:21
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:44:16
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:723:17
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:167:37
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/async/lib/async.js:652:25
    at /root/.nvm/versions/node/v4.0.0/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:887:16
[2019-02-13T16:22:46.044Z] error: Failed to stop services: Error: bitcoind process did not exit

**Comment by opiumfor** [comment]
Have you fixed this? I've just faced the same problem.

**Comment by giovangonzalez** [comment]
Hey guys, I have this same issue... any news? Thanks.
