### ISSUE TITLE
regtest p2p-cash Unsupported message command: xversion

### ISSUE THREAD

**Issue by ww8912188** [bitpay/bitcore#2000]
I'm trying test on regtest chain, when start v8, it gives below error, any clue on this issue?
```
npm run node 

> @8.0.0 node /opt/bch/bitcore
> cd packages/bitcore-node && npm start


> bitcore-node@8.0.1 start /opt/bch/bitcore/packages/bitcore-node
> npm run tsc && node build/src/server.js


> bitcore-node@8.0.1 tsc /opt/bch/bitcore/packages/bitcore-node
> npm run clean && ./node_modules/.bin/tsc


> bitcore-node@8.0.1 clean /opt/bch/bitcore/packages/bitcore-node
> rm -rf build

info: Starting Event Service
info: Starting Event Service
info: Starting API Service on port 3000
info: Starting Socket Service
info: Starting Event Service
info: Starting API Service on port 3000
info: Starting Socket Service
info: Starting P2P Manager
info: Connected to peer 127.0.0.1 chain=BCH, network=regtest
/opt/bch/bitcore/packages/bitcore-p2p-cash/lib/messages/index.js:101
    throw new Error('Unsupported message command: ' + command);
    ^

Error: Unsupported message command: xversion
    at Messages._buildFromBuffer (/opt/bch/bitcore/packages/bitcore-p2p-cash/lib/messages/index.js:101:11)
    at Messages.parseBuffer (/opt/bch/bitcore/packages/bitcore-p2p-cash/lib/messages/index.js:74:15)
    at Peer._readMessage (/opt/bch/bitcore/packages/bitcore-p2p-cash/lib/peer.js:219:31)
    at Socket.<anonymous> (/opt/bch/bitcore/packages/bitcore-p2p-cash/lib/peer.js:167:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.0.1 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitcore-node@8.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-18T12_30_16_147Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.0.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-18T12_30_16_161Z-debug.log
```

**Comment by osagga** [comment]
what bch full node are you running? `bitcoin-abc`? what version is it?

**Comment by ww8912188** [comment]
@osagga the full node is bitcoin unlimited 1.5.1.0, so it's not supported, right?

**Comment by osagga** [comment]
@ww8912188 I'm not sure actually, I have only tested it with `bitcoin-abc`.

**Comment by ww8912188** [comment]
@osagga it seems v8 need to set trustedPeers in the config file(bitcore.config.json on my side), or it will not start properly. 
Sometimes when user begin a regtest node, it may be a single isolated one. V8 will not start in this case.
Do we have a workaround for this issue? Or must I start a another regtest node as a peer? Would you please share the bch regtest bitcoin.conf if you got one so I can have a try? Many thanks!

**Comment by ww8912188** [comment]
I just figure out that regtest defaut peer number will be 18444 if specify listen=1 in the bitcoin.conf with this guide [here](https://bitcointalk.org/index.php?topic=2169215.0).
Thanks all the same, close this issue.
