### ISSUE TITLE
 throw new Error('Data still available after parsing')

### ISSUE THREAD

**Issue by Chappell-C** [bitpay/bitcore#2183]
I extended the library to dash，When I execute the npm run node，It went wrong.

```
npm run node

> @8.0.0 node /Users/chenpeng/mySelf/Bitcore-dash
> cd packages/bitcore-node && npm start


> bitcore-node@8.0.1 start /Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node
> npm run tsc && node build/src/server.js


> bitcore-node@8.0.1 tsc /Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node
> npm run clean && ./node_modules/.bin/tsc


> bitcore-node@8.0.1 clean /Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node
> rm -rf build

info: Starting Event Service
info: Starting Event Service
info: Starting API Service on port 3000
info: Starting Socket Service
info: Starting Event Service
info: Starting API Service on port 3000
info: Starting Socket Service
info: Starting Event Service
info: Starting Event Service
info: Starting API Service on port 3000
info: Starting Socket Service
info: Starting API Service on port 3000
info: Starting Socket Service
info: Starting P2P Manager
p2pWorkers.
/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/messages/utils.js:20
      throw new Error('Data still available after parsing');
      ^

Error: Data still available after parsing
    at Object.checkFinished (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/messages/utils.js:20:13)
    at VersionMessage.setPayload (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/messages/commands/version.js:71:9)
    at Function.exported.commands.(anonymous function).fromBuffer (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/messages/builder.js:110:15)
    at Messages._buildFromBuffer (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/messages/index.js:105:41)
    at Messages.parseBuffer (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/messages/index.js:75:15)
    at Peer._readMessage (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/peer.js:219:31)
    at Socket.<anonymous> (/Users/chenpeng/mySelf/Bitcore-dash/packages/bitcore-node/modules/@dashevo/dashcore-p2p/lib/peer.js:167:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.0.1 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@8.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chenpeng/.npm/_logs/2019-05-14T07_58_33_416Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.0.0 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.0.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chenpeng/.npm/_logs/2019-05-14T07_58_33_495Z-debug.log

```

When I run btc, bch, bsv, it is normal.I want to consult the reason for this error.

node version: v8.15.0
npm version: v6.4.1

Thanks。

**Comment by Chappell-C** [comment]
OK了

**Comment by changliang0931** [comment]
@Ark-Chen 
How do you do it, And I have the same problem.
