### ISSUE TITLE
Mongob issues after updating bitcorev8 to master

### ISSUE THREAD

**Issue by EthanHeilman** [bitpay/bitcore#2187]
I've been using an older version of bitcorev8 prior to tagging being introduced. We have been looking at upgrading and stood up a test service using the latest from master. This [commit specifically as the latest commit](https://github.com/bitpay/bitcore/commit/39e3a4ce63511dbdd15760e8f67e64cb344010c6).

I've been running this newer version of bitcorev8 on a test server. It repeatedly runs into an issue where it stops syncing.

Restarting bitcore resolves the problem for anywhere from 5 minutes to 3 hours before it stops syncing again. You can see in the logs that mongod is no longer receiving queries from bitcore.

Mongod at the point at which bitcore stops syncing
```
2019-05-16T14:12:12.070+0000 I WRITE    [conn100] update bitcore.coins command: { q: { mintTxid: "aec274b3
5ba08477d8f3f536279385932937adabb81446683bf6039a74021671", mintIndex: 1, spentHeight: { $lt: 0 }, chain: "
BCH", network: "mainnet" }, u: { $set: { spentTxid: "ade0d0672460d0298fb7657306283397989cec2b0ea78d565a77d
6e966752ca3", spentHeight: 582746 } }, multi: false, upsert: false } planSummary: IXSCAN { mintTxid: 1, mi
ntIndex: 1 } keysExamined:1 docsExamined:1 nMatched:1 nModified:1 keysInserted:2 keysDeleted:2 numYields:1
 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, Database: { acquireCount: { w: 2 } }, Collection: { acq
uireCount: { w: 2 } } } storage:{ data: { bytesRead: 138354, timeReadingMicros: 123381 } } 119ms
2019-05-16T14:12:12.112+0000 I WRITE    [conn97] update bitcore.coins command: { q: { mintTxid: "e86883d14
669b1f5614ddaf839c3fa5db16f28a652aedee24fb79bd7e0440e53", mintIndex: 1, spentHeight: { $lt: 0 }, chain: "B
CH", network: "mainnet" }, u: { $set: { spentTxid: "bd8c8a70d458635fa756f4abc5a547b80f7b6b01536badb9300293
fe9d94bf38", spentHeight: 582746 } }, multi: false, upsert: false } planSummary: IXSCAN { mintTxid: 1, min
tIndex: 1 } keysExamined:1 docsExamined:1 nMatched:1 nModified:1 keysInserted:2 keysDeleted:2 numYields:1 
locks:{ Global: { acquireCount: { r: 2, w: 2 } }, Database: { acquireCount: { w: 2 } }, Collection: { acqu
ireCount: { w: 2 } } } storage:{ data: { bytesRead: 342599, timeReadingMicros: 350404 } } 191ms
2019-05-16T14:12:12.167+0000 I COMMAND  [conn100] command bitcore.$cmd command: update { update: "coins", 
ordered: false, lsid: { id: UUID("9d427dff-ecc2-4d11-9375-015623032880") }, $db: "bitcore" } numYields:0 r
eslen:75 locks:{ Global: { acquireCount: { r: 59, w: 51 } }, Database: { acquireCount: { w: 51 } }, Collec
tion: { acquireCount: { w: 51 } } } storage:{ data: { bytesRead: 698599, timeReadingMicros: 92631 } } prot
ocol:op_query 790ms
2019-05-16T14:12:12.191+0000 I COMMAND  [conn97] command bitcore.$cmd command: update { update: "coins", o
rdered: false, lsid: { id: UUID("fcad4fd4-fbda-431a-9950-8e27e6816c81") }, $db: "bitcore" } numYields:0 re
slen:75 locks:{ Global: { acquireCount: { r: 57, w: 51 } }, Database: { acquireCount: { w: 51 } }, Collect
ion: { acquireCount: { w: 51 } } } storage:{ data: { bytesRead: 95305, timeReadingMicros: 76807 } } protoc
ol:op_query 813ms
2019-05-16T14:12:13.001+0000 I -        [conn7]   Index Build (background): 127380700/1345504652 9%
2019-05-16T14:12:16.003+0000 I -        [conn7]   Index Build (background): 127583700/1345504652 9%
2019-05-16T14:12:19.001+0000 I -        [conn7]   Index Build (background): 127788700/1345504652 9%
2019-05-16T14:12:22.000+0000 I -        [conn7]   Index Build (background): 127992600/1345504652 9%
2019-05-16T14:12:25.001+0000 I -        [conn7]   Index Build (background): 128198400/1345504652 9%
2019-05-16T14:12:28.000+0000 I -        [conn7]   Index Build (background): 128412100/1345504652 9%
2019-05-16T14:12:31.044+0000 I -        [conn7]   Index Build (background): 128601600/1345504652 9%
2019-05-16T14:12:34.001+0000 I -        [conn7]   Index Build (background): 128688500/1345504652 9%
2019-05-16T14:12:37.001+0000 I -        [conn7]   Index Build (background): 128853400/1345504652 9%
2019-05-16T14:12:40.002+0000 I -        [conn7]   Index Build (background): 129052400/1345504652 9%
2019-05-16T14:12:43.000+0000 I -        [conn7]   Index Build (background): 129283700/1345504652 9%
2019-05-16T14:12:46.006+0000 I -        [conn7]   Index Build (background): 129483800/1345504652 9%
2019-05-16T14:12:49.000+0000 I -        [conn7]   Index Build (background): 129676400/1345504652 9%
2019-05-16T14:12:52.000+0000 I -        [conn7]   Index Build (background): 129831700/1345504652 9%
2019-05-16T14:12:55.000+0000 I -        [conn7]   Index Build (background): 130043200/1345504652 9%
2019-05-16T14:12:58.000+0000 I -        [conn7]   Index Build (background): 130318600/1345504652 9%
2019-05-16T14:13:01.001+0000 I -        [conn7]   Index Build (background): 130562700/1345504652 9%
2019-05-16T14:13:04.000+0000 I -        [conn7]   Index Build (background): 130757900/1345504652 9%
2019-05-16T14:13:07.002+0000 I -        [conn7]   Index Build (background): 130892400/1345504652 9%
2019-05-16T14:13:10.000+0000 I -        [conn7]   Index Build (background): 131090400/1345504652 9%
2019-05-16T14:13:13.000+0000 I -        [conn7]   Index Build (background): 131302700/1345504652 9%
2019-05-16T14:13:16.002+0000 I -        [conn7]   Index Build (background): 131505400/1345504652 9%
```

Bitcore logs. Stopped syncing after block 576001
```
info: 2019-05-16 15:13:55.310 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.78 blocks/min | Height:  575995
info: 2019-05-16 15:15:43.583 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.75 blocks/min | Height:  575996
info: 2019-05-16 15:16:59.320 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.76 blocks/min | Height:  575997
info: 2019-05-16 15:18:10.486 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.76 blocks/min | Height:  575998
info: 2019-05-16 15:19:23.912 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.77 blocks/min | Height:  575999
info: 2019-05-16 15:22:18.321 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.71 blocks/min | Height:  576000
info: 2019-05-16 15:24:32.649 UTC | Syncing... | Chain: BTC | Network: mainnet |    0.68 blocks/min | Height:  576001
```

If I let it run long enough after it has stopped syncing eventually I'll see errors that the connection to mongod has timed out. 

```
info: 20:43:04 GMT+0000 (UTC) |      ::ffff:10.0.1.176 |    START |        ... |    GET |   ... | /api/status/performance
info: 20:43:04 GMT+0000 (UTC) |      ::ffff:10.0.1.176 |      END |       1 ms |    GET |   200 | /api/status/performance
error: 2019-05-15 20:43:05.881 UTC | Error syncing | Chain: BTC | Network: mainnet MongoNetworkError: connection 6 to 127.0.0.1:27017 timed out
    at Socket.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/connection/connection.js:258:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
error: 2019-05-15 20:43:05.882 UTC | Error syncing | Chain: LTC | Network: mainnet MongoNetworkError: connection 6 to 127.0.0.1:27017 timed out
    at Socket.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/connection/connection.js:258:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Unhandled Rejection at: MongoNetworkError: connection 6 to 127.0.0.1:27017 timed out
    at Socket.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/connection/connection.js:258:7)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Shutting down 12337
info: Stopping P2P Manager
info: 2019-05-15 20:43:05.930 UTC | Syncing 555 blocks | Chain: LTC | Network: mainnet
```

**Comment by micahriggan** [comment]
I think maybe an index was added since you originally started, and your mongo is trying to add this new index, while also still handling the blocks

May have to wait for it to finish this index before it starts acting right

**Comment by EthanHeilman** [comment]
The bitcore socket to mongodb times out before it finishes. I started and restarted bitcore quite a few  times. It may be that if you restart it 100 times over 2 days it gets to a point that is stable, but that still seems like a bug especially given that the older bitcorev8 code doesn't require this.

**Comment by micahriggan** [comment]
Is the index still building? 

I would wait until the index build finishes before. Your database is actively reorganizing everything, trying to sync while that's happening would probably slow it down

**Comment by EthanHeilman** [comment]
Let me try that and get back to you

**Comment by micahriggan** [comment]
Any update after the indexes finished?

**Comment by osagga** [comment]
@micahriggan yes it seems that waiting for `mongo` to finish building the new indexes and then starting the bitcore node fixes this.

I also think a fix to this would be a better timeout handling from bitcore side. Is it expected that a timeout goes unhanded and causes the node to crash? Also maybe the P2P manager shouldn't start syncing if mongo is re-indexing (I'm not sure if that's detectable to the mongo client)? what do you think?
