### ISSUE TITLE
Error: Cannot find module './build/Release/scrypt'

### ISSUE THREAD

**Issue by BoGnY** [bitpay/bitcore#2220]
I've cloned master branch, and run `npm install` without problem..
Runned even `npm run bootstrap && npm run compile` manually without errors.

Now, if I try to start node, I get this error:
```
[root@100417 ~]# cd /var/bitcore
[root@100417 bitcore]# npm run node

> @8.2.0 node /var/bitcore
> cd packages/bitcore-node && npm start

> bitcore-node@8.3.3 start /var/bitcore/packages/bitcore-node
> npm run tsc && node build/src/server.js

> bitcore-node@8.3.3 tsc /var/bitcore/packages/bitcore-node
> npm run clean && ./node_modules/.bin/tsc

> bitcore-node@8.3.3 clean /var/bitcore/packages/bitcore-node
> rm -rf build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/bitcore/packages/bitcore-node/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.3.3 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitcore-node@8.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-04T07_04_54_902Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.2.0 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.2.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-04T07_04_54_923Z-debug.log
```

The problem is that `.build/Release` dir don't exists so the node don't start...

Previously I've downloaded tag v8.3.0 and it works perfects, but this tag don't exists anymore, and now I've a lot of problem...

```
[root@100417 bitcore]# node -v
v10.16.0
[root@100417 bitcore]# npm -v
6.9.0
```

Attached logs:
[2019-06-04T07_04_54_923Z-debug.log](https://github.com/bitpay/bitcore/files/3251014/2019-06-04T07_04_54_923Z-debug.log)
[2019-06-04T07_04_54_902Z-debug.log](https://github.com/bitpay/bitcore/files/3251016/2019-06-04T07_04_54_902Z-debug.log)

**Comment by BoGnY** [comment]
Resolved, node-gyp request python 2.7 but my system han python 2.6... updated it, rebuild all and bitcore-node start 👍
