### ISSUE TITLE
can't start BWS

### ISSUE THREAD

**Issue by bitcoincashCN** [bitpay/bitcore#2240]
-----------------------------------------------------------
> bitcore-wallet-service@2.5.1 start /home/bitcoincashcn/bitcore-wallet-service
> ./start.sh
Successfully started locker/locker.js. PID=18197. Logs are at logs/locker.log
Successfully started messagebroker/messagebroker.js. PID=18198. Logs are at logs/messagebroker.log
Successfully started bcmonitor/bcmonitor.js. PID=18199. Logs are at logs/bcmonitor.log
Successfully started emailservice/emailservice.js. PID=18200. Logs are at logs/emailservice.log
Successfully started pushnotificationsservice/pushnotificationsservice.js. PID=18201. Logs are at logs/pushnotifica
tionsservice.log
Successfully started fiatrateservice/fiatrateservice.js. PID=18202. Logs are at logs/fiatrateservice.log
Successfully started bws.js. PID=18203. Logs are at logs/bws.log

-------------------------------------------------------------
logs:

bitcoincashcn@bitcore-node:~/bitcore-wallet-service$ more logs/bws.log 
/home/bitcoincashcn/bitcore-wallet-service/lib/blockchainexplorers/v8.js:174
V8.prototype.getBalance = async function (wallet, cb) {
                                ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bitcoincashcn/bitcore-wallet-service/lib/blockchainexplorer.js:9:10)

config.json
------------------------------------------------------------

bitcoincashcn@bitcore-node:~/bitcore-wallet-service$   more config.js
var config = {
  basePath: '/bws/api',
  disableLogs: false,
  port: 3232,

  storageOpts: {
    mongoDb: {
      uri: 'mongodb://localhost:27017/bws',
    },
  },
  lockOpts: {
    //  To use locker-server, uncomment this:
    lockerServer: {
      host: 'localhost',
      port: 3231,
    },
  },
  messageBrokerOpts: {
    //  To use message broker server, uncomment this:
    messageBrokerServer: {
      url: 'http://localhost:3380',
    },
  },
  blockchainExplorerOpts: {
    bch: {
     livenet: {
        provider: 'insight',
        url: 'https://oldbcl.truevisionofsatoshi.com',
      },
    },
  },
};
module.exports = config;

**Comment by bitcoincashCN** [comment]
now it fix by changing node v6.17.1 to v10 and reinstall

bitcoincashcn@bitcore-node:~/bitcore-wallet-service$ nvm ls
       v0.10.48
         v4.9.1
        v6.17.1
->     v10.16.0
         system
default -> v4.* (-> v4.9.1)
node -> stable (-> v10.16.0) (default)
stable -> 10.16 (-> v10.16.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> v10.16.0)
lts/argon -> v4.9.1
lts/boron -> v6.17.1
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.16.0
