### ISSUE TITLE
Can't NPM Install on Mac

### ISSUE THREAD

**Issue by kaning** [bitpay/bitcore#2242]
```
17941 info lifecycle @8.1.0~postinstall: Failed to exec postinstall script
17942 verbose stack Error: @8.1.0 postinstall: `npm run bootstrap && npm run compile`
17942 verbose stack Exit status 1
17942 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
17942 verbose stack     at EventEmitter.emit (events.js:200:13)
17942 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
17942 verbose stack     at ChildProcess.emit (events.js:200:13)
17942 verbose stack     at maybeClose (internal/child_process.js:1021:16)
17942 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
17943 verbose pkgid @8.1.0
17944 verbose cwd /Users/aningk/Development/bitcore
17945 verbose Darwin 18.6.0
17946 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "install"
17947 verbose node v12.4.0
17948 verbose npm  v6.9.0
17949 error code ELIFECYCLE
17950 error errno 1
17951 error @8.1.0 postinstall: `npm run bootstrap && npm run compile`
17951 error Exit status 1
17952 error Failed at the @8.1.0 postinstall script.
17952 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kaning** [comment]
I also tried downgrading my node version as well but I have the same issue

```
1 verbose stack Error: @8.1.0 postinstall: `npm run bootstrap && npm run compile`
61 verbose stack Exit status 1
61 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@10/10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
61 verbose stack     at EventEmitter.emit (events.js:198:13)
61 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@10/10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
61 verbose stack     at ChildProcess.emit (events.js:198:13)
61 verbose stack     at maybeClose (internal/child_process.js:982:16)
61 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
62 verbose pkgid @8.1.0
63 verbose cwd /Users/aningk/Development/bitcore
64 verbose Darwin 18.6.0
65 verbose argv "/usr/local/Cellar/node@10/10.16.0/bin/node" "/usr/local/bin/npm" "install"
66 verbose node v10.16.0
67 verbose npm  v6.9.0
68 error code ELIFECYCLE
69 error errno 1
70 error @8.1.0 postinstall: `npm run bootstrap && npm run compile`
70 error Exit status 1
71 error Failed at the @8.1.0 postinstall script.
```

**Comment by partyka1** [comment]
i think you didnt include actual exception that was thrown, but try removing `package-lock.json` in root directory and Run `npm install` again. Also to exclude some other issues, try to run the `npm install` on fresh clone, or run sth like `rm -rf node_modules && find . -iname "node_modules" -type d -exec rm -rf {} +` (**!!tested on osx be careful on other OS!!**) in root directory to remove all existing node_modules in the project.
