### ISSUE TITLE
Error: Invalid Address string provided

### ISSUE THREAD

**Issue by aacoinonline** [bitpay/bitcore#2273]
Blockchain monitor started
info Connected to V8 (bch/mainnet) @ https://api.bitcore.io 
info Connected to V8 (btc/testnet) @ https://api.bitcore.io 
info Connected to V8 (btc/mainnet) @ https://api.bitcore.io 
ERR! Error connecting to V8 (bch/testnet) @ http://localhost:3000 
ERR! Error connecting to V8 (bch/testnet) @ http://localhost:3000 
ERR! Error connecting to V8 (bch/testnet) @ http://localhost:3000 
ERR! Error connecting to V8 (bch/testnet) @ http://localhost:3000 
ERR! Error connecting to V8 (bch/testnet) @ http://localhost:3000 
/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/bitcore-lib-cash/lib/address.js:380
    throw new Error('Invalid Address string provided');
    ^

Error: Invalid Address string provided
    at Function.Address._transformString (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/bitcore-lib-cash/lib/address.js:380:11)
    at Address._classifyArguments (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/bitcore-lib-cash/lib/address.js:111:20)
    at new Address (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/bitcore-lib-cash/lib/address.js:77:19)
    at /Users/zhouhe/wallet/bitcore-wallet-service/lib/bchaddresstranslator.js:43:18
    at arrayMap (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/lodash/lodash.js:9556:14)
    at Function.BCHAddressTranslator.translate (/Users/zhouhe/wallet/bitcore-wallet-service/lib/bchaddresstranslator.js:41:14)
    at Socket.socket.on (/Users/zhouhe/wallet/bitcore-wallet-service/lib/blockchainexplorers/v8.js:423:58)
    at Socket.Emitter.emit (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/Users/zhouhe/wallet/bitcore-wallet-service/node_modules/socket.io-client/lib/socket.js:278:10)

**Comment by jfordnose64** [comment]
I am also dealing with this issue @aacoinonline. Did you end up finding a solution? 

Thank you!
