### ISSUE TITLE
What's wrong with this error function apply(fn, ...args) Unexpected token...

### ISSUE THREAD

**Issue by MEIGOVTECH** [bitpay/bitcore#2334]
/root/.nvm/versions/node/v4.9.1/lib/node_modules/bitcore/node_modules/_async@3.1.0@async/dist/async.js:52
    function apply(fn, ...args) {
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/.nvm/versions/node/v4.9.1/lib/node_modules/bitcore/node_modules/_insight-api@0.4.3@insight-api/lib/blocks.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by vinitshahdeo** [comment]
@MEIGOVTECH Hey, I'm also getting the same error. **Did you find any workaround?**

**Comment by olegmitrakhovich** [comment]
got the same error, anything anybody?

**Comment by olegmitrakhovich** [comment]
found this https://stackoverflow.com/questions/56802207/nodejs-syntaxerror-unexpected-token

**Comment by samoyedsun** [comment]
First, I think this question is about async's version. then I compare async's version in "node_modules/bitcore-node/package.json" and in "node_modules/insight-api/package.json", it's not same.

So I change async's version in "node_modules/insight-api/package.json"  to the same with async's version in "node_modules/bitcore-node/package.json".
Then it work.
