### ISSUE TITLE
Unhandled Rejection at: TypeError: Cannot read property 'lib' of undefined

### ISSUE THREAD

**Issue by sillyghost** [bitpay/bitcore#2342]
Hey ,
I am getting the following error on running `npm run node`

`info: Starting Event Service
info: Starting P2P Manager
Unhandled Rejection at: TypeError: Cannot read property 'lib' of undefined
    at new P2pWorker (/root/bitcore/packages/bitcore-node/build/src/services/p2p.js:69:45)
    at P2pManager.start (/root/bitcore/packages/bitcore-node/build/src/services/p2p.js:47:31)
    at Object.exports.FullClusteredWorker (/root/bitcore/packages/bitcore-node/build/src/workers/all.js:38:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Shutting down 10487
info: Stopping P2P Manager
info: Stopping Event Service` 
I am using node 8.15.0 , already ran the following commands  -
npm install
npm run bootstrap
node_modules/.bin/lerna run compile

I am using it for a forked coin , any help would be appreciated :)

**Comment by micahriggan** [comment]
You likely need to modify https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/chain.ts

In the near future, custom forks will be easier to support.

**Comment by sillyghost** [comment]
Great that worked , Thanks !
