### ISSUE TITLE
npm install not working on master branch

### ISSUE THREAD

**Issue by ianadavies** [bitpay/bitcore#2398]
Hi there,

I have just cloned bitcore and tried to run npm install on MacOS and I get the following error

```
silly saveTree ├─┬ @types/web3@1.0.19
19 silly saveTree │ └── @types/underscore@1.9.2
19 silly saveTree └── bcryptjs@2.4.3
20 verbose stack TypeError: Cannot read property 'match' of undefined
20 verbose stack     at tarballToVersion (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
20 verbose stack     at inflatableChild (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
20 verbose stack     at BB.each (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
20 verbose stack     at tryCatcher (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
20 verbose stack     at Object.gotValue (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
20 verbose stack     at Object.gotAccum (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
20 verbose stack     at Object.tryCatcher (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
20 verbose stack     at Promise._settlePromiseFromHandler (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
20 verbose stack     at Promise._settlePromise (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
20 verbose stack     at Promise._settlePromise0 (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
20 verbose stack     at Promise._settlePromises (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
20 verbose stack     at _drainQueueStep (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
20 verbose stack     at _drainQueue (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
20 verbose stack     at Async._drainQueues (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
20 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
20 verbose stack     at runCallback (timers.js:705:18)
21 verbose cwd /Users/xxx/src/stratis/bitcore/bitcore/packages/crypto-wallet-core
22 verbose Darwin 18.7.0
23 verbose argv "/Users/xxx/.nvm/versions/node/v10.16.1/bin/node" "/Users/xxx/.nvm/versions/node/v10.16.1/bin/npm" "install"
24 verbose node v10.16.1
25 verbose npm  v6.9.0
26 error Cannot read property 'match' of undefined
27 verbose exit [ 1, true ]
```
I have tried clearing node modules. using NVM and tried node versions 8, 10 and 12 all fail with the same error.

**Comment by micahriggan** [comment]
Try deleting the package-lock for crypto-wallet-core and then running npm install in that folder. We did a bunch of merges yesterday and I think the package-locks got messed up

**Comment by ianadavies** [comment]
Ok so, made a bit more progress.

BTW it seems I have to run all the commands as 'sudo' is that expected?
Now getting this.

```
src/providers/chain-state/internal/internal.ts:19:28 - error TS2307: Cannot find module 'crypto-wallet-core'.

19 import { Validation } from 'crypto-wallet-core';
                              ~~~~~~~~~~~~~~~~~~~~

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2019-09-18T13_39_11_536Z-debug.log
➜  bitcore git:(master) ✗ cd packages/bitcore-client 
➜  bitcore-client git:(master) ✗ sudo npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for crypto-wallet-core@8.7.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'bitcore-client'
npm ERR! notarget 

```
I can see the version is 8.7.3 in the package.json for crypto-wallet-core and that does now build after your instructions.

but the bootstrap still fails :/

**Comment by micahriggan** [comment]
Lerna won't install with Root, so make sure you're not on root, and then for the issue you've got there, you need to run npm installl from the root of the bitcore directory.

It will compile and link crypto-wallet-core.

**Comment by ianadavies** [comment]
Have noticed that there's been some updates recently with the package.json. 
So tired again today, now getting this.

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@10.16.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v10.16.1/bin/node" "/Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents
gyp ERR! node -v v10.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/xxx/.nvm/versions/node/v10.16.1/bin/node /Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/xxx/.nvm/versions/node/v10.16.1/bin/node" "/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
```

Looks like a mac issue?

**Comment by micahriggan** [comment]
Those sound like file system permission errors. Make sure the user that owns that folder is the same user that you're running npm install with

You can use ls -al PATH_TO_FS_EVENTS 

Make sure it's your user, and not root. if it's root you're gonna need to remove the node modules folder and reinstall without sudo

**Comment by ianadavies** [comment]
I've cloned this into a fresh directory a few times now and still keep getting the same issues. I'm running as current user, nothing special.

FYI I have just done this on an Ubuntu VM and it works fine so I think there is a Darwin issue here. do you have anyone in your team that can try this on a mac to confirm?

**Comment by ianadavies** [comment]
Anyone managed to confirm if this is an issue yet?

**Comment by adamkeinan** [comment]
hi, sorry to barge in to the discussion,
but i had a similar issue that repeated in a dev project,which i managed to resolve after two weeks of pain. 
if your using one of webpack modules i highly recommend to work with a LTS version of node and a shrinkwrap.json. 

just took a brief look at your log and its written that process x.x.x are failing to execute = > due to the fact that the node vm doesn't get the permissions to start.
the main reason for that is that the node-gyp version isn't compatible with the node version.

you can still save/clone the repo as is, and reinstall a fresh node version on a clean directories.
just in case,check your environment variables.

**Comment by skhaz** [comment]
@ianadavies I have the same issue that affects you

**Comment by micahriggan** [comment]
@ianadavies I'm on mac OSX10.14, with node 8.15, but I'm pretty sure it works with 10 as well

Can you make sure the file owners of these files all match?
```
/Users/xxx/.nvm/versions/node/v10.16.1/bin/node

 /Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js 

/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node"

/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64
```

```
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib' 
```

This error reads as if node-pre-gyp cannot create a folder at that path.
Which makes me think something wonky is going on with ` /Users/xxx/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js `

Make sure that guy has permissions to write to '/Users/xxx/src/bitcore/bitcore/packages/bitcore-lib/node_modules/fsevents/lib'

**Comment by adamkeinan** [comment]
obviously you need to isolate your node-gyp & fsevents modules an recalculate which pkg will match a lower version than @1.2.9. it also seems that you'll need to downgrade your nvm in order to rule out any installation of this two packages after cloning the repo and during npm install.
