### ISSUE TITLE
git master: Cannot find module 'websocket' (missing dependency)

### ISSUE THREAD

**Issue by jamespharvey20** [bitpay/bitcore#2441]
The output and linked to logs are from a slightly prior version, but this still occurs in git master (2019-10-01 bb284683).  nodejs 11.15.0, since 12.x is still having issues with scrypt.  npm 6.11.3.

In the top of the bitcore git repo, manually running `npm install websocket` fixes the error.  Looks like a new dependency is missing?

````
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/bitcorenew/bitcore.git/packages/crypto-wallet-core/node_modules/web3-providers-ws/src/index.js:27:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.7.4 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitcore-node@8.7.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcorenew/.npm/_logs/2019-09-30T02_27_55_180Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.7.3 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.7.3 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcorenew/.npm/_logs/2019-09-30T02_27_55_213Z-debug.log
````

The first referenced debug log is here: http://ix.io/1J3X

The second referenced debug log is here: http://ix.io/1Jfd

**Comment by micahriggan** [comment]
Try deleting your package-lock and node_modules and redoing an npm install. We may have a package-lock that doesn't have a correct link to websocket for web3. I'm not sure why that keeps happening, but it's very annoying

**Comment by jamespharvey20** [comment]
Huh, you're right.  I didn't run into this on 8.7.1.  But, deleting all package-lock and node_modules and re-running 'npm install' and 'npm run node' does get past this, without manually running 'npm install websocket'.
