### ISSUE TITLE
when i run `npm install` multiple errors occours

### ISSUE THREAD

**Issue by pavoltravnik** [bitpay/bitcore#2558]
node -v
v13.1.0
npm -v
6.12.1
debian 10

npm install

> @8.10.0 postinstall /home/ltc/bitcore
> npm run bootstrap && npm run compile

> @8.10.0 bootstrap /home/ltc/bitcore
> lerna bootstrap

lerna notice cli v3.6.0
lerna info Bootstrapping 13 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'crypto-wallet-core'
lerna ERR! npm install stdout:

> sha3@1.2.3 install /home/ltc/bitcore/packages/crypto-wallet-core/node_modules/sha3
> node-gyp rebuild

make: Entering directory '/home/ltc/bitcore/packages/crypto-wallet-core/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
make: Leaving directory '/home/ltc/bitcore/packages/crypto-wallet-core/node_modules/sha3/build'

lerna ERR! npm install stderr:
In file included from ../src/addon.cpp:4:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/addon.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)':
../src/addon.cpp:49:23: warning: 'new' of type 'SHA3Hash' with extended alignment 32 [-Waligned-new=]
    obj = new SHA3Hash();
                       ^
../src/addon.cpp:49:23: note: uses 'void* operator new(std::size_t)', which does not have an alignment parameter
../src/addon.cpp:49:23: note: use '-faligned-new' to enable C++17 over-aligned new support
../src/addon.cpp: In static member function 'static void SHA3Hash::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/addon.cpp:83:27: error: no matching function for call to 'v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)'
   target->Set(className, f);
                           ^
In file included from /home/ltc/.cache/node-gyp/13.1.0/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)'
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note:   candidate expects 3 arguments, 2 provided
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)'
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/addon.cpp:1:
../src/addon.cpp: At global scope:
/home/ltc/.cache/node-gyp/13.1.0/include/node/node.h:603:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/ltc/.cache/node-gyp/13.1.0/include/node/node.h:637:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/addon.cpp:164:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(sha3, SHA3Hash::Init)
 ^~~~~~~~~~~
In file included from /home/ltc/.cache/node-gyp/13.1.0/include/node/node.h:63,
                 from ../src/addon.cpp:1:
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/home/ltc/.cache/node-gyp/13.1.0/include/node/node_object_wrap.h:84:78:   required from here
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h:10100:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:65:61:   required from here
/home/ltc/.cache/node-gyp/13.1.0/include/node/v8.h:10100:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
make: *** [sha3.target.mk:113: Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.16.6-042stab139.44
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ltc/bitcore/packages/crypto-wallet-core/node_modules/sha3
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN crypto-wallet-core@8.10.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ltc/.npm/_logs/2019-11-14T21_58_36_255Z-debug.log

lerna ERR! npm install exited 1 in 'crypto-wallet-core'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.10.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.10.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ltc/.npm/_logs/2019-11-14T21_58_36_351Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.10.0 postinstall: `npm run bootstrap && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ltc/.npm/_logs/2019-11-14T21_58_36_391Z-debug.log

**Comment by EvilCode01** [comment]
Try it
nvm install v8.16.2
and after run
npm install

**Comment by cjrocks** [comment]
Same problem here.

**Comment by EvilCode01** [comment]
Guys just:
Step 1: nvm install v8.16.2
Step 2: ~ cd bitcore
Step 3: npm install
Step 4: npm run node
