### ISSUE TITLE
Unable to start node

### ISSUE THREAD

**Issue by Gabo1122** [bitpay/bitcore#2603]
I cloned the repo, then ran the command npm i, configured the RPC and ran npm run node, but I am having the following issue:
Error: Cannot find module './build/Debug/addon'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/bitcore/packages/bitcore-node/node_modules/heapdump/index.js:19:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/bitcore/packages/bitcore-node/src/workers/all.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcore-node@8.11.1 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@8.11.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-11-27T22_18_50_953Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.11.1 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.11.1 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-11-27T22_18_50_967Z-debug.log

**Comment by waveiron** [comment]
Same issue here, This error shows after I downgrade node to v8.16.2.

**Comment by micahriggan** [comment]
Hi, thanks for the report, haven't seen this one before, will investigate tomorrow. We likely have something in the package-lock/package.json that is causing this with the heapdump package

**Comment by micahriggan** [comment]
@waveiron does `npm i` or `npm rebuild` give any compile errors?

**Comment by Fedyano** [comment]
it happened to me too after `git pull`
`npm install` or `npm rebuild` and `npm run build`  ended successfully

**Comment by maektwain** [comment]
This seems to be an error with nodejs also if the above does not work please revert to nodejs with 10.0.x

**Comment by bilthon** [comment]
I'm having the same issue and none of the above worked. Tried with node `v12.13.1`, `v10.19.0` & `8.10.0`. Any suggestions?

**Comment by maektwain** [comment]
Try removing the old packages and run it using version 8.10 first.

**Comment by FlorinMotoc** [comment]
v10.19.0 worked ok on 2 machines (macos and ubuntu 18)
- but after a failed run, if you `npm install` & `npm run bootstrap / compile` it won't be with success.
- I deleted all node_modules (from base dir and also the ones from packages/, and rerun npm install (with bootstrap/compile if weren't already run at install - for me on ubuntu 18 + node 10.19.0 + npm 6.13.4 `postinstall` is not running after `npm install`

**Comment by maektwain** [comment]
What is the error , when you run npm install or other command.  Verified @FlorinMotoc  it works with 10 version of node js , another interesting thing I noticed when building , it was failing in root user but when trying with admin user group it was passing all the test and all the error above.

**Comment by Muggle-Du** [comment]
I've tried node@10, it didn't work either.

**Comment by galuha** [comment]
This is the same issue: https://github.com/bitpay/bitcore/issues/2856
Copying my weird solution for this:

Hi. Just stuck on this on Fedora 32 and Node v8.17.0.
We were installing simultaneously with my friend. He was using the same Fedora and node versions. For some reason he didn't get this error. Also the difference between our installations was that his 'npm install' finished from the first run. But i had to run it twice, because at first run has got some weird dependency error. On the second 'npm install' it has finished ok, but npm run node exited with the same error as yours.
So what I did, knowing that my friend managed to run bitcore on the same system just fine. I just reinstalled bitcore:
rm -rf bitcore
git clone https://github.com/bitpay/bitcore.git
git checkout master
cd bitcore
nvm install -v8.17.0
npm install
npm run node

This time npm install for some reason has finished without errors
And npm run node has started without errors also
Weird!
