### ISSUE TITLE
WebSocket,Socket.IO connect 400 Transport Error

### ISSUE THREAD

**Issue by b-m-9** [bitpay/bitcore#2716]
```
const io = require('socket.io-client');
const socket = io.connect('http://localhost:3000/');
socket.on('connect', () => {
  console.log('Connected to socket');
  socket.emit('room', '/BTC/mainnet/inv');
});
socket.on('disconnect', function (d) {
  console.log('disconnect!', d)
});
socket.on('error', function (e) {
  console.log('error!', e)
});
```
Error:
```
Connected to socket
error! { Error: xhr post error
    at XHR.Transport.onError (/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/node_modules/engine.io-client/lib/transports/polling-xhr.js:112:10)
    at Request.Emitter.emit (/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at Request.onError (/node_modules/engine.io-client/lib/transports/polling-xhr.js:313:8)
    at Timeout._onTimeout (/node_modules/engine.io-client/lib/transports/polling-xhr.js:260:18)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7) type: 'TransportError', description: 400 }
disconnect! transport error
```

**Comment by b-m-9** [comment]
Think it can be helpful for someone:

SOLVE:
const socket = io.connect('http://localhost:3000/'**, { transports: ['websocket'] }**);
