### ISSUE TITLE
Installation process error, studied for a week

### ISSUE THREAD

**Issue by CoxxA** [bitpay/bitcore#2729]
lerna notice cli v3.20.2
lerna info Bootstrapping 13 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'bitcore-client'
lerna ERR! npm install stdout:

> bcrypt@3.0.8 install /home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

Failed to execute '/home/hai/下载/node-v10.16.0-linux-x64/bin/node /home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)

lerna ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.8 and node@8.15.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error connect ECONNREFUSED 52.217.4.20:443 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/home/hai/下载/node-v10.16.0-linux-x64/bin/node" "/home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/hai/下载/node-v10.16.0-linux-x64/bin/node /home/hai/下载/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 5.3.0-40-generic
node-pre-gyp ERR! command "/home/hai/下载/node-v10.16.0-linux-x64/bin/node" "/home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hai/.local/share/Trash/files/bitcore/packages/bitcore-client/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN bitcore-client@8.16.0 No repository field.
npm WARN bitcore-client@8.16.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hai/.npm/_logs/2020-02-19T13_45_53_535Z-debug.log

lerna ERR! npm install exited 1 in 'bitcore-client'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.16.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.16.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hai/.npm/_logs/2020-02-19T13_45_53_567Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @8.16.0 postinstall: `npm run bootstrap && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @8.16.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hai/.npm/_logs/2020-02-19T13_45_53_733Z-debug.log

**Comment by CoxxA** [comment]
Ubuntu 18.04.1
node 8.15.0
npm 6.4.1

**Comment by tinshen** [comment]
suggest nodejs v10.19.0

v8、v12、v13 compile error。

**Comment by maektwain** [comment]
So, from the log error, it looks like you are in the need of build tool, so install these 

`python ,make and gc++ or other compilers also`

Why?  It require a set of working crypto libs to be compiled.
