### ISSUE TITLE
lerna ERR! npm run compile exited 1 in 'bitcore-client' error TS2339: Property 'sign' does not exist on type

### ISSUE THREAD

**Issue by ghyphtedhippie** [bitpay/bitcore#2745]
I have been trying to get an instance of this up and running have run into various issues....
The most recent... Please refer to the terminal outputs and log entries below and HELP!!
Thanks!

Terminal Outputs:
> bitcore-wallet-service@8.7.3 clean /home/server/bitcore/packages/bitcore-wallet-service
> rm -rf ./ts_build

lerna ERR! npm run compile exited 1 in 'bitcore-client'
lerna ERR! npm run compile stdout:

> bitcore-client@8.7.3 compile /home/server/bitcore/packages/bitcore-client
> npm run clean && ./node_modules/.bin/tsc

> bitcore-client@8.7.3 clean /home/server/bitcore/packages/bitcore-client
> rm -rf ./ts_build

src/client.ts(29,22): error TS2339: Property 'sign' does not exist on type 'typeof import("/home/server/bitcore/packages/bitcore-client/node_modules/@types/secp256k1/index")'.

lerna ERR! npm run compile stderr:

npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! bitcore-client@8.7.3 compile: `npm run clean && ./node_modules/.bin/tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bitcore-client@8.7.3 compile script 'npm run clean && ./node_modules/.bin/tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitcore-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && ./node_modules/.bin/tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bitcore-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/server/bitcore/packages/bitcore-client/npm-debug.log

lerna ERR! npm run compile exited 1 in 'bitcore-client'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @8.7.3 compile: `lerna run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @8.7.3 compile script 'lerna run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/server/bitcore/npm-debug.log

/home/server/bitcore/packages/bitcore-client/npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle bitcore-client@8.7.3~precompile: bitcore-client@8.7.3
6 silly lifecycle bitcore-client@8.7.3~precompile: no script for precompile, continuing
7 info lifecycle bitcore-client@8.7.3~compile: bitcore-client@8.7.3
8 verbose lifecycle bitcore-client@8.7.3~compile: unsafe-perm in lifecycle true
9 verbose lifecycle bitcore-client@8.7.3~compile: PATH: /usr/share/npm/bin/node-gyp-bin:/home/se$
10 verbose lifecycle bitcore-client@8.7.3~compile: CWD: /home/server/bitcore/packages/bitcore-cl$
11 silly lifecycle bitcore-client@8.7.3~compile: Args: [ '-c', 'npm run clean && ./node_modules/$
12 silly lifecycle bitcore-client@8.7.3~compile: Returned: code: 2  signal: null
13 info lifecycle bitcore-client@8.7.3~compile: Failed to exec compile script
14 verbose stack Error: bitcore-client@8.7.3 compile: `npm run clean && ./node_modules/.bin/tsc`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid bitcore-client@8.7.3
16 verbose cwd /home/server/bitcore/packages/bitcore-client
17 error Linux 4.15.0-88-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error bitcore-client@8.7.3 compile: `npm run clean && ./node_modules/.bin/tsc`
22 error Exit status 2
23 error Failed at the bitcore-client@8.7.3 compile script 'npm run clean && ./node_modules/.bin$
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bitcore-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && ./node_modules/.bin/tsc
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bitcore-client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bitcore-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

/home/server/bitcore/npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle @8.7.3~precompile: @8.7.3
6 silly lifecycle @8.7.3~precompile: no script for precompile, continuing
7 info lifecycle @8.7.3~compile: @8.7.3
8 verbose lifecycle @8.7.3~compile: unsafe-perm in lifecycle true
9 verbose lifecycle @8.7.3~compile: PATH: /usr/share/npm/bin/node-gyp-bin:/home/server/bitcore/n$
10 verbose lifecycle @8.7.3~compile: CWD: /home/server/bitcore
11 silly lifecycle @8.7.3~compile: Args: [ '-c', 'lerna run compile' ]
12 silly lifecycle @8.7.3~compile: Returned: code: 1  signal: null
13 info lifecycle @8.7.3~compile: Failed to exec compile script
14 verbose stack Error: @8.7.3 compile: `lerna run compile`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid @8.7.3
16 verbose cwd /home/server/bitcore
17 error Linux 4.15.0-88-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error @8.7.3 compile: `lerna run compile`
22 error Exit status 1
23 error Failed at the @8.7.3 compile script 'lerna run compile'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     lerna run compile
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tinshen** [comment]
because your node's version is to low.
suggest node's  v10.19.0
