### ISSUE TITLE
npm run node

### ISSUE THREAD

**Issue by GalaxySciTech** [bitpay/bitcore#2856]
Error: Cannot find module './build/Debug/addon'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/bitcore/packages/bitcore-node/node_modules/heapdump/index.js:19:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/bitcore/packages/bitcore-node/src/workers/all.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by PeterRogers123** [comment]
I also am coming accross this error. I suspect this has to do with the node and npm version being use hope devs get back too us! I am using cnetos 8

**Comment by galuha** [comment]
Hi. Just stuck on this on Fedora 32 and Node v8.17.0.
We were installing simultaneously with my friend. He was using the same Fedora and node versions. For some reason he didn't get this error. Also the difference between our installations was that his 'npm install' finished from the first run. But i had to run it twice, because at first run has got some weird dependency error. On the second 'npm install' it has finished ok, but npm run node exited with the same error as yours.
So what I did, knowing that my friend managed to run bitcore on the same system just fine. I just reinstalled bitcore:
rm -rf bitcore
git clone https://github.com/bitpay/bitcore.git
git checkout master
cd bitcore
nvm install -v8.17.0
npm install
npm run node

This time npm install for some reason has finished without errors
And npm run node has started without errors also
Weird!
