### ISSUE TITLE
bitcore node restart and  resync from zero

### ISSUE THREAD

**Issue by mesment** [bitpay/bitcore#2857]
After sync a few days bitcore node shutdown and  resync from zero again. Is this a bitcore bug ?

here is the bitcore error log:

```
436422\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:34:26.960600003Z"}
{"log":"{\"message\":\"2020-06-05 10:34:40.969 UTC | Syncing... | Chain: BCH | Network: mainnet |    5.02 blocks/min | Height:  436423\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:34:40.970040757Z"}
{"log":"{\"message\":\"2020-06-05 10:34:49.333 UTC | Syncing... | Chain: BCH | Network: mainnet |    5.02 blocks/min | Height:  436424\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:34:49.333455962Z"}
{"log":"{\"message\":\"2020-06-05 10:34:53.854 UTC | Syncing... | Chain: BCH | Network: mainnet |    5.03 blocks/min | Height:  436425\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:34:53.854749306Z"}
{"log":"{\"message\":\"2020-06-05 10:35:11.200 UTC | Syncing... | Chain: BCH | Network: mainnet |    5.03 blocks/min | Height:  436426\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:35:11.00300234Z"}
{"log":"{\"message\":\"2020-06-05 10:35:34.213 UTC | Syncing... | Chain: BCH | Network: mainnet |    5.02 blocks/min | Height:  436427\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:35:34.213592569Z"}
{"log":"{\"message\":\"2020-06-05 10:35:41.721 UTC | Syncing... | Chain: BCH | Network: mainnet |    5.03 blocks/min | Height:  436429\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:35:41.722046103Z"}
{"log":"Unhandled Rejection at: BulkWriteError: database dropped\n","stream":"stderr","time":"2020-06-05T10:36:05.147703881Z"}
{"log":"    at resultHandler (/bitcore/packages/bitcore-node/node_modules/mongodb/lib/bulk/ordered.js:464:11)\n","stream":"stderr","time":"2020-06-05T10:36:05.147737754Z"}
{"log":"    at /bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/connection/pool.js:531:18\n","stream":"stderr","time":"2020-06-05T10:36:05.147749278Z"}
{"log":"    at process._tickCallback (internal/process/next_tick.js:61:11)\n","stream":"stderr","time":"2020-06-05T10:36:05.147755843Z"}
{"log":"Shutting down 50\n","stream":"stdout","time":"2020-06-05T10:36:05.148055182Z"}
{"log":"{\"message\":\"Stopping P2P Manager\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:36:05.148287683Z"}
{"log":"Shutting down 50\n","stream":"stdout","time":"2020-06-05T10:36:05.477734975Z"}
{"log":"Unhandled Rejection at: Error: Syncing Node Renewal Failure\n","stream":"stderr","time":"2020-06-05T10:36:05.477737909Z"}
{"log":"    at BitcoinP2PWorker.refreshSyncingNode (/bitcore/packages/bitcore-node/src/services/p2p.ts:105:15)\n","stream":"stderr","time":"2020-06-05T10:36:05.477778486Z"}
{"log":"    at process._tickCallback (internal/process/next_tick.js:68:7)\n","stream":"stderr","time":"2020-06-05T10:36:05.477784632Z"}
{"log":"{\"message\":\"Stopping Event Service\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:36:05.477959235Z"}
{"log":"{\"message\":\"Stopping P2P Manager\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:36:05.477998206Z"}
{"log":"{\"message\":\"Stopping P2P Manager\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:36:11.8217694Z"}
{"log":"\n","stream":"stdout","time":"2020-06-05T10:36:34.759668171Z"}
{"log":"\u003e bitcore-node@8.20.3 start /bitcore/packages/bitcore-node\n","stream":"stdout","time":"2020-06-05T10:36:34.759715872Z"}
{"log":"\u003e npm run tsc \u0026\u0026 node build/src/server.js\n","stream":"stdout","time":"2020-06-05T10:36:34.759723974Z"}
{"log":"\n","stream":"stdout","time":"2020-06-05T10:36:34.75972998Z"}
{"log":"\n","stream":"stdout","time":"2020-06-05T10:36:35.25099341Z"}
{"log":"\u003e bitcore-node@8.20.3 tsc /bitcore/packages/bitcore-node\n","stream":"stdout","time":"2020-06-05T10:36:35.251020508Z"}
{"log":"\u003e npm run clean \u0026\u0026 tsc\n","stream":"stdout","time":"2020-06-05T10:36:35.251027981Z"}
{"log":"\n","stream":"stdout","time":"2020-06-05T10:36:35.251034476Z"}
{"log":"\n","stream":"stdout","time":"2020-06-05T10:36:35.585249896Z"}
{"log":"\u003e bitcore-node@8.20.3 clean /bitcore/packages/bitcore-node\n","stream":"stdout","time":"2020-06-05T10:36:35.585285305Z"}
{"log":"\u003e rm -rf build\n","stream":"stdout","time":"2020-06-05T10:36:35.585295223Z"}
{"log":"\n","stream":"stdout","time":"2020-06-05T10:36:35.585302835Z"}
{"log":"{\"message\":\"Starting Event Service\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:02.448334132Z"}
{"log":"{\"message\":\"Starting P2P Manager\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:02.457079492Z"}
{"log":"{\"message\":\"Starting BCH p2p worker\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:02.457518863Z"}
{"log":"(node:83) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n","stream":"stderr","time":"2020-06-05T10:37:02.779834904Z"}
{"log":"{\"message\":\"2020-06-05 10:37:02.807 UTC | Connected to peer: 172.17.0.1:18333 | Chain: BCH | Network: mainnet\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:02.808362263Z"}
{"log":"{\"message\":\"This worker is now the syncing node for BCH mainnet\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:03.982893034Z"}
{"log":"{\"message\":\"2020-06-05 10:37:04.110 UTC | Syncing 2000 blocks | Chain: BCH | Network: mainnet\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:04.111177905Z"}
{"log":"{\"message\":\"2020-06-05 10:37:05.152 UTC | Syncing... | Chain: BCH | Network: mainnet |  806.14 blocks/min | Height:      14\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:05.152844746Z"}
{"log":"{\"message\":\"2020-06-05 10:37:06.175 UTC | Syncing... | Chain: BCH | Network: mainnet | 1220.34 blocks/min | Height:      42\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:06.176040436Z"}
{"log":"{\"message\":\"2020-06-05 10:37:07.191 UTC | Syncing... | Chain: BCH | Network: mainnet | 1363.19 blocks/min | Height:      70\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:07.191872573Z"}
{"log":"{\"message\":\"2020-06-05 10:37:08.203 UTC | Syncing... | Chain: BCH | Network: mainnet | 1495.24 blocks/min | Height:     102\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:08.203546302Z"}
{"log":"{\"message\":\"2020-06-05 10:37:09.212 UTC | Syncing... | Chain: BCH | Network: mainnet | 1564.09 blocks/min | Height:     133\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:09.212876514Z"}
{"log":"{\"message\":\"2020-06-05 10:37:10.219 UTC | Syncing... | Chain: BCH | Network: mainnet | 1964.31 blocks/min | Height:     200\",\"level\":\"info\"}\n","stream":"stdout","time":"2020-06-05T10:37:10.219189243Z"}
{"log":"{\"message\":\"2020-06-05 10:37:11.221 UTC | Syncing... | Chain: BCH | Network: mainnet | 2666.29 blocks/min | Height:  
```

my bitcore.config.json file:

```
{
 "bitcoreNode": {
   "modules": ["./bitcoin", "./bitcoin-cash"],
   "services": {
      "api": {
        "rateLimiter": {
          "disabled": true
        }
      }
    },
    "chains": {
      "BCH": {
        "mainnet": {
          "trustedPeers": [
            {
              "host": "172.17.0.1",
              "port": 18333
            }
          ],
          "rpc": {
            "host": "172.17.0.1",
            "port": 18332,
            "username": "abc",
            "password": "abc"
          }
        }
      }
    }
  }
}
```

docker-compose.yml

```
version: '3'
services:
  database:
    image: mongo:4.0.14-xenial
    ports: 
    - 27017:27017
    volumes: 
      - /data/bch-apidata/mongodata:/data/db
  bitcoincashabc:
    image: bitcoincash:latest
    restart: always
    ports:
      - 28332:18332
      - 28333:18333
    volumes:
      - /data/bch-apidata/blockchain-data:/bitcoindata
  bitcore-node:
    build: .
    image: bitcore-node:latest
    restart: always
    links:
      - database
      - bitcoincashabc
    ports:
      - 8100:8100
      - 3002:3000
    environment:
      - DB_HOST=database
      - BITCORE_CONFIG_PATH=/bitcore/bitcore.config.json

```

**Comment by micahriggan** [comment]
You might want to check and make sure that someone didn't access your database. Database dropped implies that something dropped the mongo collection, completely deleting all of the data.
