### ISSUE TITLE
Unhandled Rejection at: Error: Returned error: invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash

### ISSUE THREAD

**Issue by noateden** [bitpay/bitcore#2862]
I can not start bitcore-node when connect with my Ethereum Private Network. But, I can start bitcore-node when connect to Ganache Blockchain.
When I bootstrap bitcore-node whith command ```npm run node``` I get this error:
```text
Unhandled Rejection at: Error: Returned error: invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash
    at Object.ErrorResponse (/home/pmtoan/workspace/bitcore/packages/bitcore-node/node_modules/crypto-rpc/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/pmtoan/workspace/bitcore/packages/bitcore-node/node_modules/crypto-rpc/node_modules/web3-core-requestmanager/src/index.js:140:36
    at exports.XMLHttpRequest.request.onreadystatechange (/home/pmtoan/workspace/bitcore/packages/bitcore-node/node_modules/crypto-rpc/node_modules/web3-providers-http/src/index.js:104:13)
    at exports.XMLHttpRequest.dispatchEvent (/home/pmtoan/workspace/bitcore/packages/bitcore-node/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/pmtoan/workspace/bitcore/packages/bitcore-node/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/pmtoan/workspace/bitcore/packages/bitcore-node/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by micahriggan** [comment]
Can you cd into packages/bitcore-node and do `npm run debug` and see what method it's calling?

If I had to guess, it's doing `get block 0` to get the block at height 0, but the private network is expecting that height to be a hash

**Comment by pmtoan** [comment]
@micahriggan , this happens when I try to connect to Ethereum node use RPC (HTTP protocol). But when I use WS, this error solved. Can the current version support the HTTP protocol?
