### ISSUE TITLE
Unhandled Rejection at: Error: CONNECTION ERROR: Couldn't connect to node on WS.

### ISSUE THREAD

**Issue by pmtoan** [bitpay/bitcore#2867]
When I try to sync data from my ETH node with WS protocol, after 1 day, I got this error:
```
Unhandled Rejection at: Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/usr/src/app/packages/bitcore-node/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/usr/src/app/packages/bitcore-node/node_modules/web3/node_modules/web3-providers-ws/src/index.js:255:48)
    at W3CWebSocket.connection.onclose (/usr/src/app/packages/bitcore-node/node_modules/web3/node_modules/web3-providers-ws/src/index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/src/app/packages/bitcore-node/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/usr/src/app/packages/bitcore-node/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/usr/src/app/packages/bitcore-node/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.drop (/usr/src/app/packages/bitcore-node/node_modules/@web3-js/websocket/lib/WebSocketConnection.js:475:14)
    at /usr/src/app/packages/bitcore-node/node_modules/@web3-js/websocket/lib/WebSocketConnection.js:303:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Shutting down 65
{"message":"Stopping P2P Manager","level":"info"}
connection not open on send()
connection not open on send()
making a new connection```

Does anyone have ideas with this error?

**Comment by micahriggan** [comment]
Your node could have stopped accepting ws connections. Try restarting the parity/geth node

**Comment by pmtoan** [comment]
@micahriggan, Thanks for your reply. But when a resync from block 0, it is okay. But currently, it has broken as an above error. I also restarted the GETH node. Can you have any ideas or suggestions for me?

**Comment by pmtoan** [comment]
This error because of WebSocket message size limitation. Just increase WebSocket Client's message to solve this issue. Thanks for your help.

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/pull/2744

Sounds like this was a similar issue

**Comment by solaris-rig** [comment]
> This error because of WebSocket message size limitation. Just increase WebSocket Client's message to solve this issue. Thanks for your help.

how do you solve it? i guess im having similar issue. thanks in advance

**Comment by pmtoan** [comment]
> > This error because of WebSocket message size limitation. Just increase WebSocket Client's message to solve this issue. Thanks for your help.
> 
> how do you solve it? i guess im having similar issue. thanks in advance

Check this pull request: https://github.com/bitpay/bitcore/pull/2744
