### ISSUE TITLE
npm run node  ERROR

### ISSUE THREAD

**Issue by youngqqcn** [bitpay/bitcore#2876]
- CentOS 7
- nodejs: v10.21.0
- bitcore version:  master (commit: 734107b5312f9ca91bf878a1aa6e76166dee4e83) 

```
[root@blockchain-node2 bitcore]# 
[root@blockchain-node2 bitcore]# npm run node

> @8.20.4 node /data/bitcore
> cd packages/bitcore-node && npm start


> bitcore-node@8.20.4 start /data/bitcore/packages/bitcore-node
> npm run tsc && node build/src/server.js


> bitcore-node@8.20.4 tsc /data/bitcore/packages/bitcore-node
> npm run clean && tsc


> bitcore-node@8.20.4 clean /data/bitcore/packages/bitcore-node
> rm -rf build

error TS2688: Cannot find type definition file for 'mocha'.


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitcore-node@8.20.4 tsc: `npm run clean && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bitcore-node@8.20.4 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T07_55_44_539Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitcore-node@8.20.4 start: `npm run tsc && node build/src/server.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bitcore-node@8.20.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T07_55_44_574Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @8.20.4 node: `cd packages/bitcore-node && npm start`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @8.20.4 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T07_55_44_609Z-debug.log
[root@blockchain-node2 bitcore]# 
```

log

```
 1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/usr/local/node/node-v10.21.0-linux-x64/bin/node',
  3 1 verbose cli   '/usr/local/bin/npm',
  4 1 verbose cli   'run',
  5 1 verbose cli   'node' ]
  6 2 info using npm@6.14.4
  7 3 info using node@v10.21.0
  8 4 verbose run-script [ 'prenode', 'node', 'postnode' ]
  9 5 info lifecycle @8.20.4~prenode: @8.20.4
 10 6 info lifecycle @8.20.4~node: @8.20.4
 11 7 verbose lifecycle @8.20.4~node: unsafe-perm in lifecycle true
 12 8 verbose lifecycle @8.20.4~node: PATH: /usr/local/node/node-v10.21.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-    bin:/data/bitcore/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 13 9 verbose lifecycle @8.20.4~node: CWD: /data/bitcore
 14 10 silly lifecycle @8.20.4~node: Args: [ '-c', 'cd packages/bitcore-node && npm start' ]
 15 11 silly lifecycle @8.20.4~node: Returned: code: 2  signal: null
 16 12 info lifecycle @8.20.4~node: Failed to exec node script
 17 13 verbose stack Error: @8.20.4 node: `cd packages/bitcore-node && npm start`
 18 13 verbose stack Exit status 2
 19 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/node-v10.21.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle    /index.js:332:16)
 20 13 verbose stack     at EventEmitter.emit (events.js:198:13)
 21 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/node-v10.21.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle    /lib/spawn.js:55:14)
 22 13 verbose stack     at ChildProcess.emit (events.js:198:13)
 23 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
 24 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
 25 14 verbose pkgid @8.20.4
 26 15 verbose cwd /data/bitcore
 27 16 verbose Linux 3.10.0-1062.9.1.el7.x86_64
 28 17 verbose argv "/usr/local/node/node-v10.21.0-linux-x64/bin/node" "/usr/local/bin/npm" "run" "node"
 29 18 verbose node v10.21.0
 30 19 verbose npm  v6.14.4
 31 20 error code ELIFECYCLE
 32 21 error errno 2
 33 22 error @8.20.4 node: `cd packages/bitcore-node && npm start`
 34 22 error Exit status 2
 35 23 error Failed at the @8.20.4 node script.
 36 23 error This is probably not a problem with npm. There is likely additional logging output above.
 37 24 verbose exit [ 2, true ]

```

**Comment by youngqqcn** [comment]
- CentOS 7 
- node:  v10.21.0
- bitcore version: master (commit: 734107b)


```
npm cache clean --force
rm -rf node_modules
rm -rf package-lock.json
```

In China  the mirror of taobao is faster than npm default mirror, so I  repalce `npm` with `cnpm` 
``` 
npm config set registry https://registry.npm.taobao.org

npm install -g cnpm --registry=https://registry.npm.taobao.org

cnpm install 
```

if logs show eslint@^4.9.0 is not installed , install it :

`cnpm install  cnpm install eslint@4.9.0`
  

than

```
cnpm  run node 
```


IT' WORK!
