### ISSUE TITLE
Serialization error since a week ago

### ISSUE THREAD

**Issue by angelobl** [bitpay/bitcore#2931]
I've been using bitcore-lib library for the past 3 months with no issues whatsoever and haven't touched the code in all of that time. Last week I started getting this serialization error after trying to send a transaction:

```
Error
    at new NodeError (E:\backup\Proyect\Proyect\node_modules\bitcore-lib\lib\errors\index.js:20:41)
    at Transaction.getSerializationError (E:\backup\Proyect\Proyect\node_modules\bitcore-lib\lib\transaction\transaction.js:222:22)
    at Transaction.checkedSerialize (E:\backup\Proyect\Proyect\node_modules\bitcore-lib\lib\transaction\transaction.js:185:33)
    at Transaction.serialize (E:\backup\Proyect\Proyect\node_modules\bitcore-lib\lib\transaction\transaction.js:169:17)    
    at E:\backup\Proyect\Proyect\transaction.js:76:54
    at Request._callback (E:\backup\Proyect\Proyect\node_modules\bitcore-explorers\lib\insight.js:80:12)
    at Request.self.callback (E:\backup\Proyect\Proyect\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (E:\backup\Proyect\Proyect\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (E:\backup\Proyect\Proyect\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'undefined - For more information please see: https://bitcore.io/api/lib/transaction#serialization-checks'
}
```
Ive tried with numerous addresses and no luck. This is the first time I'm getting this error and everything was working properly a week ago, what could be going on?

**Comment by micahriggan** [comment]
Input selection and setting the fee would be my first two guesses. Can you output the JSON before trying to serialize to make sure it looks as you'd expect

**Comment by angelobl** [comment]
> Input selection and setting the fee would be my first two guesses. Can you output the JSON before trying to serialize to make sure it looks as you'd expect

It just fixed itself last week

**Comment by michaelessiet** [comment]
Has this error resurfaced itself for you? It's currently happening to one of our users and we're unable to recreate it on any other device
