### ISSUE TITLE
Error "Point does not lie on the curve" is thrown when using multiple currency libs in the same environment

### ISSUE THREAD

**Issue by tayler-king** [bitpay/bitcore#3128]
This is following on from a previous issue on the old repository for bitcore-lib: https://github.com/bitpay/bitcore-lib/pull/238

When using multiple currency libs in the same environment (bitcoin, doge, litecoin, etc). this error gets thrown when calling `new bitcore.HDPrivateKey().toString()`.

```js
Error: Point does not lie on the curve
    at Point.validate (/root/app/node_modules/bitcore-lib-doge/lib/crypto/point.js:123:11)
    at new PublicKey (/root/app/node_modules/bitcore-lib/lib/publickey.js:53:14)
    at Function.PublicKey.fromPrivateKey (/root/app/node_modules/bitcore-lib/lib/publickey.js:221:10)
    at PrivateKey.toPublicKey (/root/app/node_modules/bitcore-lib/lib/privatekey.js:361:30)
    at HDPrivateKey._buildFromBuffers (/root/app/node_modules/bitcore-lib/lib/hdprivatekey.js:486:30)
    at HDPrivateKey._buildFromObject (/root/app/node_modules/bitcore-lib/lib/hdprivatekey.js:376:15)
    at new HDPrivateKey (/root/app/node_modules/bitcore-lib/lib/hdprivatekey.js:61:10)
    at Function.HDPrivateKey.fromSeed (/root/app/node_modules/bitcore-lib/lib/hdprivatekey.js:422:10)
    at HDPrivateKey._generateRandomly (/root/app/node_modules/bitcore-lib/lib/hdprivatekey.js:396:23)
    at new HDPrivateKey (/root/app/node_modules/bitcore-lib/lib/hdprivatekey.js:45:17)
 ```

Is there any workaround to this?

**Comment by Kondax** [comment]
Unfortunately the above patch didn't fix the issue.

**Comment by rowandh** [comment]
This might help: https://github.com/bitpay/bitcore/pull/3205

**Comment by tayler-king** [comment]
> This might help: https://github.com/bitpay/bitcore/pull/3205

Thanks, I'll take a look.
