### ISSUE TITLE
bitcore-node: MongoError: server instance pool was destroyed

### ISSUE THREAD

**Issue by swtrse** [bitpay/bitcore#3243]
When running bitcore-node against my mongodb isntance the service logs are flooded with these messages

```
Unhandled Rejection at: MongoError: server instance pool was destroyed
     at basicWriteValidations (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/topologies/server.js:698:41)
     at Server.update (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/topologies/server.js:834:16)
     at Server.update (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/topologies/topology_base.js:326:25)
     at updateDocuments (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/operations/collection_ops.js:1344:19)
     at /home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/utils.js:437:24
     at new Promise (<anonymous>)
     at executeOperation (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/utils.js:432:10)
     at Collection.update (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/collection.js:829:10)
     at EthTransactionModel.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/models/transaction.ts:230:29)
     at step (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:62:23)
     at Object.next (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:43:53)
     at /home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:37:71
     at new Promise (<anonymous>)
     at __awaiter (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:33:12)
     at EthTransactionModel.pruneMempool (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:387:16)
     at EthTransactionModel.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/models/transaction.ts:94:26)
     at step (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:62:23)
     at Object.next (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:43:53)
     at /home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:37:71
     at new Promise (<anonymous>)
     at __awaiter (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:33:12)
     at EthTransactionModel.batchImport (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:173:16)
     at EthP2pWorker.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/p2p/p2p.ts:188:18)
     at step (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/p2p/p2p.js:56:23)
     at Object.next (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/p2p/p2p.js:37:53)
     at /home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/p2p/p2p.js:31:71
     at new Promise (<anonymous>)
     at __awaiter (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/p2p/p2p.js:27:12)
```
in pair with
```
Unhandled Rejection at: MongoError: Topology was destroyed
     at nextFunction (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/cursor.js:603:27)
     at Cursor.next (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb-core/lib/cursor.js:824:3)
     at Cursor._next (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/cursor.js:211:36)
     at fetchDocs (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/operations/cursor_ops.js:211:12)
     at toArray (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/operations/cursor_ops.js:241:3)
     at /home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/utils.js:437:24
     at new Promise (<anonymous>)
     at executeOperation (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/utils.js:432:10)
     at Cursor.toArray (/home/bitcore/bitcore/packages/bitcore-node/node_modules/mongodb/lib/cursor.js:818:10)
     at EthTransactionModel.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/models/transaction.ts:190:109)
     at step (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:62:23)
     at Object.next (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:43:53)
     at /home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:37:71
     at new Promise (<anonymous>)
     at __awaiter (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:33:12)
     at /home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/models/transaction.ts:188:50
     at Array.map (<anonymous>)
     at EthTransactionModel.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/models/transaction.ts:188:20)
     at step (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:62:23)
     at Object.next (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:43:53)
     at /home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:37:71
     at new Promise (<anonymous>)
     at __awaiter (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:33:12)
     at EthTransactionModel.addTransactions (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:330:16)
     at EthTransactionModel.<anonymous> (/home/bitcore/bitcore/packages/bitcore-node/src/modules/ethereum/models/transaction.ts:95:30)
     at step (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:62:23)
     at Object.next (/home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:43:53)
     at /home/bitcore/bitcore/packages/bitcore-node/build/src/modules/ethereum/models/transaction.js:37:71
```

The only thin I changed what the bitcore-node setup. Link to MongoDB is correct because despite the errors the service writes data into the database at, least some.

**Comment by swtrse** [comment]
Based on the errors I can confirm that the errors only show when bitcore-node tries to access my geth node for db import

**Comment by swtrse** [comment]
Ok, I found out the reason for that error is that geth does not support the method " trace_block".
However with cease support of OpenEthereum what node should we run instead?

**Comment by swtrse** [comment]
Erigon node works fine as far as I can tell
