### ISSUE TITLE
multi-crypto conflicts

### ISSUE THREAD

**Issue by brucewang997** [bitpay/bitcore#3246]
Point does not lie on the curve
    at Point.validate (/xxx/node_modules/bitcore-lib/lib/crypto/point.js:119:11)
    at Function.fromX (/xxx/node_modules/bitcore-lib-doge/lib/crypto/point.js:50:9)

I  am using both bitcore-lib and bitcore-lib-doge,  conflict happens. modified Point prototype may cause conflicts

**Comment by bplunkert** [comment]
I think this looks like a duplicate of #3128 which may have been resolved in #3205

**Comment by escottalexander** [comment]
@brucewang997 Also, Bitcore-lib-doge has been deprecated because Bitcore-Lib covers both Bitcoin and Doge. Thanks @bplunkert

**Comment by kajoseph** [comment]
@escottalexander I believe you mean bitcore-p2p-doge. Bitcore-lib-doge is still in use.
