### ISSUE TITLE
Error: Non-base58 character

### ISSUE THREAD

**Issue by jaxonknight3** [bitpay/bitcore#3340]
Please help happens when i try to upload assets
 at Object.decode (C:\Users\jaxon\solana-nft\metaplex\js\packages\cli\node_modules\base-x\src\index.js:111:11)
    at new PublicKey (C:\Users\jaxon\solana-nft\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\publickey.ts:56:30)
    at getCandyMachineV2Config (C:\Users\jaxon\solana-nft\metaplex\js\packages\cli\src\helpers\various.ts:152:9)
    at Command.<anonymous> (C:\Users\jaxon\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:155:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by kajoseph** [comment]
Hello, it looks like you most likely have a bad implementation of `@solana/web3.js`'s publickey and you're trying to feed something into it that is not a public key. If you're sure of your implemention, I suggest you open an issue at the appropriate solana-webe.js repo with a code snippet:
https://github.com/solana-labs/solana-web3.js
