### ISSUE TITLE
npm run build fail

### ISSUE THREAD

**Issue by Lbt777** [bitpay/bitcore#3473]
`v16.13.0`
`1) ECDSA
       signing and verification
         #verify
           should verify a valid signature, and unverify an invalid signature:
     TypeError: Cannot read properties of undefined (reading 'gt')
      at ECDSA.sigError (lib\crypto\ecdsa.js:168:11)
      at ECDSA.verify (lib\crypto\ecdsa.js:271:13)
      at Function.ECDSA.verify (lib\crypto\ecdsa.js:293:6)
      at Context.<anonymous> (test\crypto\ecdsa.js:261:15)
      at callFn (node_modules\_mocha@6.2.3@mocha\lib\runnable.js:387:21)
      at Test.Runnable.run (node_modules\_mocha@6.2.3@mocha\lib\runnable.js:379:7)
      at C:\Users\Administrator\Desktop\bitcore-lib\node_modules\_mocha@6.2.3@mocha\lib\runner.js:653:12
      at next (node_modules\_mocha@6.2.3@mocha\lib\runner.js:447:14)
      at C:\Users\Administrator\Desktop\bitcore-lib\node_modules\_mocha@6.2.3@mocha\lib\runner.js:457:7
      at next (node_modules\_mocha@6.2.3@mocha\lib\runner.js:362:14)
      at Immediate._onImmediate (node_modules\_mocha@6.2.3@mocha\lib\runner.js:425:5)
      at processImmediate (node:internal/timers:464:21)

[09:39:02] 'testmocha' errored after 15 s
[09:39:02] Error in plugin "gulp-mocha"
Message:
    There were test failures
Details:
    domainEmitter: [object Object]
    domainThrown: false

[09:39:02] 'default' errored after 15 s`

**Comment by kajoseph** [comment]
Please try with Node v12. We haven't added support for v16 yet

**Comment by Lbt777** [comment]
> Please try with Node v12. We haven't added support for v16 yet
The same question
How to solve the problem
thanks

![image](https://user-images.githubusercontent.com/46510415/199141796-48155576-bf59-48b4-a7b9-9b0c0cece0a5.png)

**Comment by panchengj** [comment]
> Please try with Node v12. We haven't added support for v16 yet

does the bitcore support doge? i runed a bitcore for dogecoin,but can't call some rpc like: 
 localhost:3000/api/DOGE/testnet/fee/2 ,
 localhost:3000/api/DOGE/testnet/tx/send 

some other rpc could call ,like :  
localhost:3000/api/DOGE/testnet/block/tip ,
 localhost:3000/api/DOGE/testnet/tx?blockHeight=12

how could i fix this ?
